import 'package:flutter/material.dart';
import 'package:flutterapp/test1app/generatedframe2widget/generated/GeneratedGroup25Widget5.dart';
import 'package:flutterapp/test1app/generatedframe2widget/generated/GeneratedRectangle365Widget2.dart';
import 'package:flutterapp/test1app/generatedframe2widget/generated/GeneratedGroup31Widget2.dart';
import 'package:flutterapp/test1app/generatedframe2widget/generated/GeneratedGroup28Widget2.dart';
import 'package:flutterapp/test1app/generatedframe2widget/generated/GeneratedGroup30Widget2.dart';
import 'package:flutterapp/test1app/generatedframe2widget/generated/GeneratedGroup34Widget2.dart';
import 'package:flutterapp/test1app/generatedframe2widget/generated/GeneratedGroup33Widget2.dart';
import 'package:flutterapp/test1app/generatedframe2widget/generated/GeneratedGroup35Widget2.dart';
import 'package:flutterapp/test1app/generatedframe2widget/generated/GeneratedGroup29Widget2.dart';
import 'package:flutterapp/test1app/generatedframe2widget/generated/GeneratedGroup27Widget2.dart';
import 'package:flutterapp/test1app/generatedframe2widget/generated/GeneratedGroup365Widget.dart';
import 'package:flutterapp/test1app/generatedframe2widget/generated/GeneratedGroup32Widget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/test1app/generatedframe2widget/generated/GeneratedImage1Widget1.dart';
import 'package:flutterapp/test1app/generatedframe2widget/generated/GeneratedGroup26Widget3.dart';
import 'package:flutterapp/test1app/generatedframe2widget/generated/Generated140AmazingDesignScreensWidget.dart';
import 'package:flutterapp/test1app/generatedframe2widget/generated/GeneratedGroup24Widget5.dart';

/* Frame Frame2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1640.5,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1800.0,
                      height: 1360.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 252, 106, 67),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width = constraints.maxWidth;

                                final double height =
                                    constraints.maxHeight * 1.0012469123391543;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: 0,
                                      y: 0,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle365Widget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width = constraints.maxWidth;

                                final double height = constraints.maxHeight;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: 0,
                                      y: 0,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedImage1Widget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.16277777777777777;

                                final double height =
                                    constraints.maxHeight * 0.44779411764705884;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.027777777777777776,
                                      y: constraints.maxHeight *
                                          0.048161764705882355,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroup27Widget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.16277777777777777;

                                final double height =
                                    constraints.maxHeight * 0.44779411764705884;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.41833333333333333,
                                      y: constraints.maxHeight *
                                          0.048161764705882355,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroup29Widget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.16277777777777777;

                                final double height =
                                    constraints.maxHeight * 0.44779411764705884;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.8088888888888889,
                                      y: constraints.maxHeight *
                                          0.048161764705882355,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroup34Widget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.16277777777777777;

                                final double height =
                                    constraints.maxHeight * 0.44779411764705884;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.027777777777777776,
                                      y: constraints.maxHeight *
                                          0.5216911764705883,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroup28Widget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.16277777777777777;

                                final double height =
                                    constraints.maxHeight * 0.44779411764705884;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.42,
                                      y: constraints.maxHeight *
                                          0.5216911764705883,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroup30Widget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.16277777777777777;

                                final double height =
                                    constraints.maxHeight * 0.44779411764705884;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.8122222222222222,
                                      y: constraints.maxHeight *
                                          0.5216911764705883,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroup35Widget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.16277777777777777;

                                final double height =
                                    constraints.maxHeight * 0.44779411764705884;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.2238888888888889,
                                      y: constraints.maxHeight *
                                          -0.18860294117647058,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroup24Widget5(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.16277777777777777;

                                final double height =
                                    constraints.maxHeight * 0.44779411764705884;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.6161111111111112,
                                      y: constraints.maxHeight *
                                          -0.18860294117647058,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroup31Widget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.16277777777777777;

                                final double height =
                                    constraints.maxHeight * 0.44779411764705884;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.2238888888888889,
                                      y: constraints.maxHeight *
                                          0.2849264705882353,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroup25Widget5(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.16277777777777777;

                                final double height =
                                    constraints.maxHeight * 0.44779411764705884;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.6161111111111112,
                                      y: constraints.maxHeight *
                                          0.2849264705882353,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroup32Widget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.16277777777777777;

                                final double height =
                                    constraints.maxHeight * 0.44779411764705884;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.2238888888888889,
                                      y: constraints.maxHeight *
                                          0.7584558823529411,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroup26Widget3(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.16277777777777777;

                                final double height =
                                    constraints.maxHeight * 0.44779411764705884;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.6161111111111112,
                                      y: constraints.maxHeight *
                                          0.7584558823529411,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroup33Widget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width = constraints.maxWidth;

                                final double height =
                                    constraints.maxHeight * 1.0012469123391543;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: 0,
                                      y: 0,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroup365Widget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 506.5,
                              top: 1105.80126953125,
                              right: null,
                              bottom: null,
                              width: 789.0,
                              height: 208.0,
                              child: Generated140AmazingDesignScreensWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
