import 'package:flutter/material.dart';
import 'package:flutterapp/test1app/generatedpaymentfailwidget1/generated/GeneratedFrame134Widget51.dart';
import 'package:flutterapp/test1app/generatedpaymentfailwidget1/generated/GeneratedBookWidget40.dart';
import 'package:flutterapp/test1app/generatedpaymentfailwidget1/generated/GeneratedRectangle393Widget35.dart';
import 'package:flutterapp/test1app/generatedpaymentfailwidget1/generated/Generated000Widget5.dart';
import 'package:flutterapp/test1app/generatedpaymentfailwidget1/generated/GeneratedBackWidget70.dart';
import 'package:flutterapp/test1app/generatedpaymentfailwidget1/generated/Generated\$1000Widget12.dart';
import 'package:flutterapp/test1app/generatedpaymentfailwidget1/generated/GeneratedTotalWidget5.dart';
import 'package:flutterapp/test1app/generatedpaymentfailwidget1/generated/Generated035Widget6.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/test1app/generatedpaymentfailwidget1/generated/GeneratedIcon3d__691Widget1.dart';
import 'package:flutterapp/test1app/generatedpaymentfailwidget1/generated/GeneratedEllipse68Widget73.dart';
import 'package:flutterapp/test1app/generatedpaymentfailwidget1/generated/GeneratedRectangle392Widget25.dart';
import 'package:flutterapp/test1app/generatedpaymentfailwidget1/generated/Generated\$1000Widget11.dart';
import 'package:flutterapp/test1app/generatedpaymentfailwidget1/generated/GeneratedFrame135Widget7.dart';
import 'package:flutterapp/test1app/generatedpaymentfailwidget1/generated/GeneratedYoucanstartreadingyourbookwheneveryouwantWidget3.dart';
import 'package:flutterapp/test1app/generatedpaymentfailwidget1/generated/GeneratedGroup344Widget6.dart';
import 'package:flutterapp/test1app/generatedpaymentfailwidget1/generated/GeneratedTaxFeesWidget5.dart';
import 'package:flutterapp/test1app/generatedpaymentfailwidget1/generated/GeneratedRectangle302Widget16.dart';
import 'package:flutterapp/test1app/generatedpaymentfailwidget1/generated/GeneratedPaymentfailedWidget1.dart';
import 'package:flutterapp/test1app/generatedpaymentfailwidget1/generated/GeneratedRectangle358Widget33.dart';

/* Frame Payment Fail
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPaymentFailWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 820.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Image.asset(
                  "assets/images/d2208bf6a31299c56f9babdcd0a8d0f9cc6385ee.png",
                  color: null,
                  fit: BoxFit.cover,
                  width: 375.0,
                  height: 820.0,
                  colorBlendMode: BlendMode.dstATop,
                ),
              ),
              Positioned(
                left: 0.0009765625,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 820.0,
                child: GeneratedRectangle392Widget25(),
              ),
              Positioned(
                left: 29.1884765625,
                top: 46.48046875,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse68Widget73(),
              ),
              Positioned(
                left: 43.0,
                top: 58.98046875,
                right: null,
                bottom: null,
                width: 8.892169952392578,
                height: 15.0,
                child: GeneratedBackWidget70(),
              ),
              Positioned(
                left: 71.0,
                top: 291.28369140625,
                right: null,
                bottom: null,
                width: 235.0,
                height: 40.0,
                child:
                    GeneratedYoucanstartreadingyourbookwheneveryouwantWidget3(),
              ),
              Positioned(
                left: 101.4638671875,
                top: 250.06591796875,
                right: null,
                bottom: null,
                width: 179.0,
                height: 32.0,
                child: GeneratedPaymentfailedWidget1(),
              ),
              Positioned(
                left: 47.43368148803711,
                top: -3.4287109375,
                right: null,
                bottom: null,
                width: 304.4345703125,
                height: 304.4345703125,
                child: GeneratedIcon3d__691Widget1(),
              ),
              Positioned(
                left: 29.0009765625,
                top: 370.45068359375,
                right: null,
                bottom: null,
                width: 316.998779296875,
                height: 209.46368408203125,
                child: GeneratedRectangle358Widget33(),
              ),
              Positioned(
                left: 29.0009765625,
                top: 591.13232421875,
                right: null,
                bottom: null,
                width: 316.998779296875,
                height: 64.41000366210938,
                child: GeneratedRectangle393Widget35(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.134083984375;

                  final double height =
                      constraints.maxHeight * 0.03763611956340511;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.13066666666666665,
                        y: constraints.maxHeight * 0.7413493830983232,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup344Widget6(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 49.0,
                top: null,
                right: null,
                bottom: null,
                width: 275.5570983886719,
                height: 0.6036523580551147,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: 103.61,
                    z: 0,
                    child: GeneratedRectangle302Widget16()),
              ),
              Positioned(
                left: 49.0,
                top: 395.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 24.0,
                child: GeneratedBookWidget40(),
              ),
              Positioned(
                left: 274.0,
                top: 395.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 24.0,
                child: Generated$1000Widget11(),
              ),
              Positioned(
                left: 274.0,
                top: 534.0751953125,
                right: null,
                bottom: null,
                width: 57.0,
                height: 24.0,
                child: Generated$1000Widget12(),
              ),
              Positioned(
                left: 289.0,
                top: 434.1630859375,
                right: null,
                bottom: null,
                width: 42.0,
                height: 24.0,
                child: Generated000Widget5(),
              ),
              Positioned(
                left: 49.0,
                top: 434.4541015625,
                right: null,
                bottom: null,
                width: 79.0,
                height: 21.0,
                child: GeneratedTaxFeesWidget5(),
              ),
              Positioned(
                left: 111.1728515625,
                top: 612.33740234375,
                right: null,
                bottom: null,
                width: 49.0,
                height: 24.0,
                child: Generated035Widget6(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.3333333333333333;

                  final double height =
                      constraints.maxHeight * 0.020731707317073172;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.536,
                        y: constraints.maxHeight * 0.5791563452743902,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFrame134Widget51(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.17066666666666666;

                  final double height =
                      constraints.maxHeight * 0.020731707317073172;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.6948177083333333,
                        y: constraints.maxHeight * 0.7498017101753048,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFrame135Widget7(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 49.0,
                top: 534.0751953125,
                right: null,
                bottom: null,
                width: 41.0,
                height: 24.0,
                child: GeneratedTotalWidget5(),
              )
            ]),
      ),
    ));
  }
}
