import 'package:flutter/material.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget11/generated/GeneratedRectangle394Widget88.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget11/generated/GeneratedRectangle390Widget50.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget11/generated/GeneratedGroup301Widget3.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget11/generated/GeneratedRectangle393Widget38.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget11/generated/GeneratedGroup300Widget4.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget11/generated/GeneratedBookcoverWidget210.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget11/generated/GeneratedShare1Widget1.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget11/generated/GeneratedBookcoverWidget209.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame Book review
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBookreviewWidget11 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 820.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 236, 240, 245),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height = constraints.maxHeight;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.0000026041666666666666,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle394Widget88(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0009765625,
                top: -0.00006103515625,
                right: null,
                bottom: null,
                width: 375.0,
                height: 820.0,
                child: GeneratedRectangle393Widget38(),
              ),
              Positioned(
                left: 50.87579345703125,
                top: 128.32174682617188,
                right: null,
                bottom: null,
                width: 273.24749755859375,
                height: 390.6455383300781,
                child: GeneratedBookcoverWidget209(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height = constraints.maxHeight;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.0000026041666666666666,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle390Widget50(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 129.6943359375,
                top: 542.50341796875,
                right: null,
                bottom: null,
                width: 101.0,
                height: 42.299072265625,
                child: GeneratedGroup300Widget4(),
              ),
              Positioned(
                left: -0.00006103515625,
                top: 503.12286376953125,
                right: null,
                bottom: null,
                width: 375.0,
                height: 316.8771667480469,
                child: GeneratedShare1Widget1(),
              ),
              Positioned(
                left: 22.75362777709961,
                top: 517.79833984375,
                right: null,
                bottom: null,
                width: 30.78543472290039,
                height: 42.008445739746094,
                child: GeneratedBookcoverWidget210(),
              ),
              Positioned(
                left: 66.5390625,
                top: 521.5078125,
                right: null,
                bottom: null,
                width: 101.0,
                height: 38.299072265625,
                child: GeneratedGroup301Widget3(),
              )
            ]),
      ),
    ));
  }
}
