import 'package:flutter/material.dart';
import 'package:flutterapp/test1app/generatedfriendwidget1/generated/GeneratedBackgroudWidget7.dart';
import 'package:flutterapp/test1app/generatedfriendwidget1/generated/GeneratedTotalReadingWidget1.dart';
import 'package:flutterapp/test1app/generatedfriendwidget1/generated/GeneratedKeepreadingWidget2.dart';
import 'package:flutterapp/test1app/generatedfriendwidget1/generated/Generated23Widget2.dart';
import 'package:flutterapp/test1app/generatedfriendwidget1/generated/GeneratedEllipse67Widget8.dart';
import 'package:flutterapp/test1app/generatedfriendwidget1/generated/GeneratedRectangle390Widget24.dart';
import 'package:flutterapp/test1app/generatedfriendwidget1/generated/GeneratedHrWidget1.dart';
import 'package:flutterapp/test1app/generatedfriendwidget1/generated/GeneratedGroup251Widget6.dart';
import 'package:flutterapp/test1app/generatedfriendwidget1/generated/GeneratedEllipse66Widget12.dart';
import 'package:flutterapp/test1app/generatedfriendwidget1/generated/GeneratedRectangle352Widget2.dart';
import 'package:flutterapp/test1app/generatedfriendwidget1/generated/GeneratedRectangle392Widget14.dart';
import 'package:flutterapp/test1app/generatedfriendwidget1/generated/GeneratedEllipse64Widget3.dart';
import 'package:flutterapp/test1app/generatedfriendwidget1/generated/GeneratedPatriciaMillerWidget1.dart';
import 'package:flutterapp/test1app/generatedfriendwidget1/generated/GeneratedCollectionsWidget11.dart';
import 'package:flutterapp/test1app/generatedfriendwidget1/generated/Generated1873Widget1.dart';
import 'package:flutterapp/test1app/generatedfriendwidget1/generated/GeneratedEllipse90Widget1.dart';
import 'package:flutterapp/test1app/generatedfriendwidget1/generated/GeneratedEllipse68Widget42.dart';
import 'package:flutterapp/test1app/generatedfriendwidget1/generated/GeneratedBackWidget39.dart';
import 'package:flutterapp/test1app/generatedfriendwidget1/generated/GeneratedVectorWidget366.dart';
import 'package:flutterapp/test1app/generatedfriendwidget1/generated/GeneratedRectangle355Widget2.dart';
import 'package:flutterapp/test1app/generatedfriendwidget1/generated/GeneratedRectangle358Widget11.dart';
import 'package:flutterapp/test1app/generatedfriendwidget1/generated/GeneratedTotalReadWidget1.dart';
import 'package:flutterapp/test1app/generatedfriendwidget1/generated/GeneratedComponent7Widget3.dart';
import 'package:flutterapp/test1app/generatedfriendwidget1/generated/GeneratedEllipse73Widget2.dart';
import 'package:flutterapp/test1app/generatedfriendwidget1/generated/GeneratedGroup299Widget1.dart';
import 'package:flutterapp/test1app/generatedfriendwidget1/generated/GeneratedReadingWidget2.dart';
import 'package:flutterapp/test1app/generatedfriendwidget1/generated/GeneratedEllipse69Widget13.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/test1app/generatedfriendwidget1/generated/GeneratedSettingsWidget10.dart';
import 'package:flutterapp/test1app/generatedfriendwidget1/generated/GeneratedEllipse74Widget1.dart';

/* Frame friend
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFriendWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 820.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 822.2915649414062,
                child: GeneratedRectangle358Widget11(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 380.0,
                height: 820.0,
                child: GeneratedBackgroudWidget7(),
              ),
              Positioned(
                left: 326.0,
                top: 578.9442138671875,
                right: null,
                bottom: null,
                width: 276.99884033203125,
                height: 124.38690185546875,
                child: GeneratedRectangle352Widget2(),
              ),
              Positioned(
                left: 336.85009765625,
                top: 610.0194091796875,
                right: null,
                bottom: null,
                width: 298.6991882324219,
                height: 149.36297607421875,
                child: GeneratedRectangle355Widget2(),
              ),
              Positioned(
                left: 28.5322265625,
                top: 468.63177490234375,
                right: null,
                bottom: null,
                width: 316.998779296875,
                height: 315.8452453613281,
                child: GeneratedGroup251Widget6(),
              ),
              Positioned(
                left: 27.87353515625,
                top: 423.7637939453125,
                right: null,
                bottom: null,
                width: 88.0,
                height: 24.0,
                child: GeneratedCollectionsWidget11(),
              ),
              Positioned(
                left: 28.7822265625,
                top: 46.086212158203125,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse68Widget42(),
              ),
              Positioned(
                left: 305.828125,
                top: 46.086212158203125,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse66Widget12(),
              ),
              Positioned(
                left: 28.828125,
                top: 99.65243530273438,
                right: null,
                bottom: null,
                width: 99.0,
                height: 99.0,
                child: GeneratedEllipse64Widget3(),
              ),
              Positioned(
                left: 29.1240234375,
                top: 267.5433349609375,
                right: null,
                bottom: null,
                width: 317.000244140625,
                height: 135.0,
                child: GeneratedKeepreadingWidget2(),
              ),
              Positioned(
                left: 207.5662384033203,
                top: 346.6907958984375,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEllipse69Widget13(),
              ),
              Positioned(
                left: 187.5662384033203,
                top: 346.6907958984375,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEllipse73Widget2(),
              ),
              Positioned(
                left: 167.5662384033203,
                top: 346.6907958984375,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEllipse74Widget1(),
              ),
              Positioned(
                left: 28.16943359375,
                top: 232.7088165283203,
                right: null,
                bottom: null,
                width: 65.0,
                height: 24.0,
                child: GeneratedReadingWidget2(),
              ),
              Positioned(
                left: 148.1240234375,
                top: 112.08251953125,
                right: null,
                bottom: null,
                width: 165.0,
                height: 32.0,
                child: GeneratedPatriciaMillerWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.15466666666666667;

                  final double height =
                      constraints.maxHeight * 0.042772376828077364;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.6022565104166666,
                        y: constraints.maxHeight * 0.1827004595500667,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated1873Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.088;

                  final double height =
                      constraints.maxHeight * 0.042772376828077364;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.39466666666666667,
                        y: constraints.maxHeight * 0.18197371320026676,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated23Widget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 226.923828125,
                top: 178.31689453125,
                right: null,
                bottom: null,
                width: 84.0,
                height: 19.0,
                child: GeneratedTotalReadingWidget1(),
              ),
              Positioned(
                left: 284.1302490234375,
                top: 162.559326171875,
                right: null,
                bottom: null,
                width: 18.0,
                height: 22.0,
                child: GeneratedHrWidget1(),
              ),
              Positioned(
                left: 148.0,
                top: 178.31689453125,
                right: null,
                bottom: null,
                width: 65.0,
                height: 19.0,
                child: GeneratedTotalReadWidget1(),
              ),
              Positioned(
                left: 44.0,
                top: 58.980224609375,
                right: null,
                bottom: null,
                width: 8.892169952392578,
                height: 15.0,
                child: GeneratedBackWidget39(),
              ),
              Positioned(
                left: 68.4815673828125,
                top: 186.548095703125,
                right: null,
                bottom: null,
                width: 19.7780704498291,
                height: 19.7780704498291,
                child: GeneratedEllipse90Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.02745531463623047;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      10.295742988586426;

                  double percentHeight = 0.010003389963289587;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      8.202779769897461;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.1952607421875,
                        translateY: constraints.maxHeight * 0.2345557236089939,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget366())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.039707310994466144;

                  final double height =
                      constraints.maxHeight * 0.018292682926829267;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8490213216145833,
                        y: constraints.maxHeight * 0.07144656297637195,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedSettingsWidget10(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 256.0,
                top: 46.086212158203125,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse67Widget8(),
              ),
              Positioned(
                left: 267.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 18.0,
                height: 18.0,
                child: GeneratedComponent7Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height = constraints.maxHeight;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.0000026041666666666666,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle390Widget24(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0009765625,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 820.0,
                child: GeneratedRectangle392Widget14(),
              ),
              Positioned(
                left: 0.4765625,
                top: 586.1157836914062,
                right: null,
                bottom: null,
                width: 374.63916015625,
                height: 273.4867248535156,
                child: GeneratedGroup299Widget1(),
              )
            ]),
      ),
    ));
  }
}
