import 'package:flutter/material.dart';
import 'package:flutterapp/test1app/generatednofriendwidget2/generated/GeneratedRectangle358Widget47.dart';
import 'package:flutterapp/test1app/generatednofriendwidget2/generated/GeneratedBackWidget87.dart';
import 'package:flutterapp/test1app/generatednofriendwidget2/generated/GeneratedEllipse68Widget91.dart';
import 'package:flutterapp/test1app/generatednofriendwidget2/generated/GeneratedEllipse76Widget5.dart';
import 'package:flutterapp/test1app/generatednofriendwidget2/generated/GeneratedFindyourclosefriendFacebookorInstagramandstartwiththemo1.dart';
import 'package:flutterapp/test1app/generatednofriendwidget2/generated/GeneratedEllipse73Widget18.dart';
import 'package:flutterapp/test1app/generatednofriendwidget2/generated/GeneratedEllipse74Widget17.dart';
import 'package:flutterapp/test1app/generatednofriendwidget2/generated/GeneratedGroup278Widget7.dart';
import 'package:flutterapp/test1app/generatednofriendwidget2/generated/GeneratedEllipse83Widget3.dart';
import 'package:flutterapp/test1app/generatednofriendwidget2/generated/GeneratedEllipse77Widget5.dart';
import 'package:flutterapp/test1app/generatednofriendwidget2/generated/GeneratedGroup285Widget3.dart';
import 'package:flutterapp/test1app/generatednofriendwidget2/generated/GeneratedEllipse78Widget4.dart';
import 'package:flutterapp/test1app/generatednofriendwidget2/generated/GeneratedEllipse71Widget14.dart';
import 'package:flutterapp/test1app/generatednofriendwidget2/generated/GeneratedEllipse75Widget6.dart';
import 'package:flutterapp/test1app/generatednofriendwidget2/generated/GeneratedEllipse74Widget16.dart';
import 'package:flutterapp/test1app/generatednofriendwidget2/generated/GeneratedGroup279Widget7.dart';
import 'package:flutterapp/test1app/generatednofriendwidget2/generated/GeneratedGroup286Widget3.dart';
import 'package:flutterapp/test1app/generatednofriendwidget2/generated/GeneratedGroup280Widget7.dart';
import 'package:flutterapp/test1app/generatednofriendwidget2/generated/GeneratedEllipse73Widget19.dart';
import 'package:flutterapp/test1app/generatednofriendwidget2/generated/GeneratedEllipse84Widget3.dart';
import 'package:flutterapp/test1app/generatednofriendwidget2/generated/GeneratedEllipse70Widget12.dart';
import 'package:flutterapp/test1app/generatednofriendwidget2/generated/GeneratedEllipse66Widget35.dart';
import 'package:flutterapp/test1app/generatednofriendwidget2/generated/GeneratedEllipse72Widget13.dart';
import 'package:flutterapp/test1app/generatednofriendwidget2/generated/GeneratedEllipse79Widget4.dart';
import 'package:flutterapp/test1app/generatednofriendwidget2/generated/GeneratedEllipse72Widget14.dart';
import 'package:flutterapp/test1app/generatednofriendwidget2/generated/GeneratedEllipse81Widget3.dart';
import 'package:flutterapp/test1app/generatednofriendwidget2/generated/GeneratedEllipse80Widget3.dart';
import 'package:flutterapp/test1app/generatednofriendwidget2/generated/GeneratedEllipse82Widget3.dart';
import 'package:flutterapp/test1app/generatednofriendwidget2/generated/GeneratedMessageWidget11.dart';
import 'package:flutterapp/test1app/generatednofriendwidget2/generated/GeneratedEllipse85Widget3.dart';

/* Frame No friend
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNofriendWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 820.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 18, 18, 18),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 818.0,
                child: GeneratedRectangle358Widget47(),
              ),
              Positioned(
                left: 305.828125,
                top: 46.086212158203125,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse66Widget35(),
              ),
              Positioned(
                left: 316.828125,
                top: 58.73486328125,
                right: null,
                bottom: null,
                width: 18.0,
                height: 18.0,
                child: GeneratedMessageWidget11(),
              ),
              Positioned(
                left: 109.3671875,
                top: 125.45789337158203,
                right: null,
                bottom: null,
                width: 68.89441680908203,
                height: 68.89441680908203,
                child: GeneratedGroup278Widget7(),
              ),
              Positioned(
                left: 295.5078125,
                top: 164.03204345703125,
                right: null,
                bottom: null,
                width: 60.64054870605469,
                height: 60.64054870605469,
                child: GeneratedGroup280Widget7(),
              ),
              Positioned(
                left: 103.01513671875,
                top: 216.66647338867188,
                right: null,
                bottom: null,
                width: 168.97064208984375,
                height: 168.97064208984375,
                child: GeneratedGroup279Widget7(),
              ),
              Positioned(
                left: 55.9404296875,
                top: 164.44894409179688,
                right: null,
                bottom: null,
                width: 29.903379440307617,
                height: 29.903379440307617,
                child: GeneratedEllipse70Widget12(),
              ),
              Positioned(
                left: 282.067138671875,
                top: 337.67132568359375,
                right: null,
                bottom: null,
                width: 43.761009216308594,
                height: 43.761009216308594,
                child: GeneratedEllipse79Widget4(),
              ),
              Positioned(
                left: 92.8251953125,
                top: 201.3140869140625,
                right: null,
                bottom: null,
                width: 16.542011260986328,
                height: 16.542011260986328,
                child: GeneratedEllipse77Widget5(),
              ),
              Positioned(
                left: 64.778076171875,
                top: 322.4627685546875,
                right: null,
                bottom: null,
                width: 16.542011260986328,
                height: 16.542011260986328,
                child: GeneratedEllipse85Widget3(),
              ),
              Positioned(
                left: 191.301513671875,
                top: 161.1283721923828,
                right: null,
                bottom: null,
                width: 29.284536361694336,
                height: 29.284536361694336,
                child: GeneratedEllipse78Widget4(),
              ),
              Positioned(
                left: 32.531982421875,
                top: 230.95787048339844,
                right: null,
                bottom: null,
                width: 62.713436126708984,
                height: 62.713436126708984,
                child: GeneratedEllipse71Widget14(),
              ),
              Positioned(
                left: 33.4453125,
                top: 356.7299499511719,
                right: null,
                bottom: null,
                width: 69.56971740722656,
                height: 69.56971740722656,
                child: GeneratedEllipse72Widget13(),
              ),
              Positioned(
                left: 172.756591796875,
                top: 408.0682067871094,
                right: null,
                bottom: null,
                width: 82.91639709472656,
                height: 82.91639709472656,
                child: GeneratedEllipse73Widget18(),
              ),
              Positioned(
                left: 294.26953125,
                top: 248.3928985595703,
                right: null,
                bottom: null,
                width: 63.11702346801758,
                height: 63.11702346801758,
                child: GeneratedEllipse74Widget16(),
              ),
              Positioned(
                left: 28.828125,
                top: 46.086181640625,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse68Widget91(),
              ),
              Positioned(
                left: 29.00048828125,
                top: 720.0,
                right: null,
                bottom: null,
                width: 316.999267578125,
                height: 64.56744384765625,
                child: GeneratedGroup285Widget3(),
              ),
              Positioned(
                left: 29.00048828125,
                top: 639.1226196289062,
                right: null,
                bottom: null,
                width: 316.999267578125,
                height: 64.5673828125,
                child: GeneratedGroup286Widget3(),
              ),
              Positioned(
                left: 236.75439453125,
                top: 125.45789337158203,
                right: null,
                bottom: null,
                width: 40.51271057128906,
                height: 40.51271057128906,
                child: GeneratedEllipse75Widget6(),
              ),
              Positioned(
                left: 260.2646484375,
                top: 394.76873779296875,
                right: null,
                bottom: null,
                width: 34.00486755371094,
                height: 34.00486755371094,
                child: GeneratedEllipse83Widget3(),
              ),
              Positioned(
                left: 339.14599609375,
                top: 325.5469665527344,
                right: null,
                bottom: null,
                width: 34.00486755371094,
                height: 34.00486755371094,
                child: GeneratedEllipse84Widget3(),
              ),
              Positioned(
                left: 259.241455078125,
                top: 184.04164123535156,
                right: null,
                bottom: null,
                width: 20.621339797973633,
                height: 20.621339797973633,
                child: GeneratedEllipse76Widget5(),
              ),
              Positioned(
                left: 312.273681640625,
                top: 391.5148010253906,
                right: null,
                bottom: null,
                width: 45.112770080566406,
                height: 45.112770080566406,
                child: GeneratedEllipse72Widget14(),
              ),
              Positioned(
                left: 0.0,
                top: 297.21484375,
                right: null,
                bottom: null,
                width: 50.495826721191406,
                height: 50.495826721191406,
                child: GeneratedEllipse73Widget19(),
              ),
              Positioned(
                left: 114.23681640625,
                top: 399.800537109375,
                right: null,
                bottom: null,
                width: 42.4342041015625,
                height: 42.4342041015625,
                child: GeneratedEllipse74Widget17(),
              ),
              Positioned(
                left: 81.320068359375,
                top: 445.7228088378906,
                right: null,
                bottom: null,
                width: 27.850875854492188,
                height: 27.850875854492188,
                child: GeneratedEllipse80Widget3(),
              ),
              Positioned(
                left: 133.139404296875,
                top: 459.64825439453125,
                right: null,
                bottom: null,
                width: 21.349853515625,
                height: 21.349853515625,
                child: GeneratedEllipse81Widget3(),
              ),
              Positioned(
                left: 288.048828125,
                top: 445.7228088378906,
                right: null,
                bottom: null,
                width: 21.349853515625,
                height: 21.349853515625,
                child: GeneratedEllipse82Widget3(),
              ),
              Positioned(
                left: 46.778076171875,
                top: 558.3496704101562,
                right: null,
                bottom: null,
                width: 300.0,
                height: 40.0,
                child:
                    GeneratedFindyourclosefriendFacebookorInstagramandstartwiththemo1(),
              ),
              Positioned(
                left: 44.0,
                top: 58.980224609375,
                right: null,
                bottom: null,
                width: 8.892169952392578,
                height: 15.0,
                child: GeneratedBackWidget87(),
              )
            ]),
      ),
    ));
  }
}
