import 'package:flutter/material.dart';
import 'package:flutterapp/test1app/generatedreadingwidget/generated/GeneratedGroupWidget121.dart';
import 'package:flutterapp/test1app/generatedreadingwidget/generated/GeneratedRectangle32Widget14.dart';
import 'package:flutterapp/test1app/generatedreadingwidget/generated/GeneratedEllipse68Widget25.dart';
import 'package:flutterapp/test1app/generatedreadingwidget/generated/GeneratedBackWidget25.dart';
import 'package:flutterapp/test1app/generatedreadingwidget/generated/GeneratedGroup256Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/test1app/generatedreadingwidget/generated/GeneratedTagcateWidget130.dart';
import 'package:flutterapp/test1app/generatedreadingwidget/generated/GeneratedContrarytopopularbeliefLoremIpsumisnotsimplyrandomtextI.dart';
import 'package:flutterapp/test1app/generatedreadingwidget/generated/GeneratedEllipse66Widget1.dart';
import 'package:flutterapp/test1app/generatedreadingwidget/generated/GeneratedGroup33Widget90.dart';
import 'package:flutterapp/test1app/generatedreadingwidget/generated/GeneratedGroup384Widget1.dart';
import 'package:flutterapp/test1app/generatedreadingwidget/generated/GeneratedGroup164Widget1.dart';
import 'package:flutterapp/test1app/generatedreadingwidget/generated/GeneratedGroup161Widget.dart';
import 'package:flutterapp/test1app/generatedreadingwidget/generated/GeneratedTagcateWidget131.dart';
import 'package:flutterapp/test1app/generatedreadingwidget/generated/GeneratedGroup66Widget.dart';
import 'package:flutterapp/test1app/generatedreadingwidget/generated/GeneratedGroup385Widget1.dart';
import 'package:flutterapp/test1app/generatedreadingwidget/generated/GeneratedRectangle328Widget2.dart';

/* Frame Reading
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedReadingWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 820.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 236, 240, 245),
                      ),
                    ),
                    Positioned(
                      left: -71.62319946289062,
                      top: -94.66595458984375,
                      right: null,
                      bottom: null,
                      width: 519.1555786132812,
                      height: 667.8228149414062,
                      child: GeneratedRectangle32Widget14(),
                    ),
                    Positioned(
                      left: 0.45458984375,
                      top: 419.5834045410156,
                      right: null,
                      bottom: null,
                      width: 375.0,
                      height: 799.4166259765625,
                      child: GeneratedRectangle328Widget2(),
                    ),
                    Positioned(
                      left: 130.14892578125,
                      top: 356.2869873046875,
                      right: null,
                      bottom: null,
                      width: 101.0,
                      height: 42.299072265625,
                      child: GeneratedGroup33Widget90(),
                    ),
                    Positioned(
                      left: 29.454574584960938,
                      top: 732.380859375,
                      right: null,
                      bottom: null,
                      width: 76.0,
                      height: 19.0,
                      child: GeneratedGroup161Widget(),
                    ),
                    Positioned(
                      left: 29.45458984375,
                      top: 767.368896484375,
                      right: null,
                      bottom: null,
                      width: 318.0,
                      height: 192.19744873046875,
                      child:
                          GeneratedContrarytopopularbeliefLoremIpsumisnotsimplyrandomtextI(),
                    ),
                    Positioned(
                      left: 29.46875,
                      top: 46.48046875,
                      right: null,
                      bottom: null,
                      width: 40.0,
                      height: 40.0,
                      child: GeneratedEllipse68Widget25(),
                    ),
                    Positioned(
                      left: 44.0,
                      top: 58.980224609375,
                      right: null,
                      bottom: null,
                      width: 8.892169952392578,
                      height: 15.0,
                      child: GeneratedBackWidget25(),
                    ),
                    Positioned(
                      left: 305.828125,
                      top: 46.08642578125,
                      right: null,
                      bottom: null,
                      width: 40.0,
                      height: 40.0,
                      child: GeneratedEllipse66Widget1(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.011760009765625;

                        final double height =
                            constraints.maxHeight * 0.024390248554508862;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.8625338541666666,
                              y: constraints.maxHeight * 0.06839746149574838,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedGroupWidget121(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 28.9139404296875,
                      top: 102.099365234375,
                      right: null,
                      bottom: null,
                      width: 317.24249267578125,
                      height: 262.79205322265625,
                      child: GeneratedGroup66Widget(),
                    ),
                    Positioned(
                      left: 26.53125,
                      top: 445.2474670410156,
                      right: null,
                      bottom: null,
                      width: 150.88999938964844,
                      height: 197.20150756835938,
                      child: GeneratedGroup384Widget1(),
                    ),
                    Positioned(
                      left: 182.33770751953125,
                      top: 445.2474670410156,
                      right: null,
                      bottom: null,
                      width: 176.58795166015625,
                      height: 197.20150756835938,
                      child: GeneratedGroup385Widget1(),
                    ),
                    Positioned(
                      left: 28.50048828125,
                      top: 666.296142578125,
                      right: null,
                      bottom: null,
                      width: 81.0,
                      height: 19.0,
                      child: GeneratedGroup164Widget1(),
                    ),
                    Positioned(
                      left: 29.0,
                      top: 696.3243408203125,
                      right: null,
                      bottom: null,
                      width: 50.0,
                      height: 17.0,
                      child: GeneratedTagcateWidget130(),
                    ),
                    Positioned(
                      left: 87.0,
                      top: 696.4935302734375,
                      right: null,
                      bottom: null,
                      width: 58.0,
                      height: 17.0,
                      child: GeneratedTagcateWidget131(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0625,
              top: 745.0,
              right: null,
              bottom: null,
              width: 374.99981689453125,
              height: 75.0,
              child: GeneratedGroup256Widget(),
            )
          ]),
    ));
  }
}
