import 'package:flutter/material.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget/generated/GeneratedRectangle368Widget74.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget/generated/GeneratedEllipse69Widget.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget/generated/GeneratedEllipse71Widget.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget/generated/GeneratedGroup33Widget35.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget/generated/GeneratedIc24sortWidget.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget/generated/GeneratedBackgroudWidget2.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget/generated/GeneratedCollectionsWidget.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget/generated/GeneratedBookWidget8.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget/generated/GeneratedBookWidget9.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget/generated/GeneratedBookWidget7.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget/generated/GeneratedSynthesizefavoritebooksyourwayEveryonecanseeandsharethi.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget/generated/GeneratedGroup251Widget.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget/generated/GeneratedRectangle352Widget.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget/generated/GeneratedBookWidget12.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget/generated/GeneratedBookWidget11.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget/generated/GeneratedBookWidget10.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget/generated/GeneratedRectangle355Widget.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget/generated/GeneratedBookWidget4.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget/generated/GeneratedBookWidget6.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget/generated/GeneratedBookWidget13.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget/generated/GeneratedSettingsWidget2.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget/generated/GeneratedAllBookWidget.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget/generated/GeneratedBookWidget5.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget/generated/GeneratedBottom_barWidget3.dart';

/* Frame Library
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLibraryWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 3628.73486328125,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 375.0,
                            height: 1885.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 236, 240, 245),
                                    ),
                                  ),
                                  Positioned(
                                    left: 0.5,
                                    top: -0.26513671875,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 3629.0,
                                    child: GeneratedBackgroudWidget2(),
                                  ),
                                  Positioned(
                                    left: 29.0,
                                    top: 102.762939453125,
                                    right: null,
                                    bottom: null,
                                    width: 115.0,
                                    height: 42.0,
                                    child: GeneratedGroup33Widget35(),
                                  ),
                                  Positioned(
                                    left: 29.0,
                                    top: 153.053466796875,
                                    right: null,
                                    bottom: null,
                                    width: 319.0001220703125,
                                    height: 38.0,
                                    child:
                                        GeneratedSynthesizefavoritebooksyourwayEveryonecanseeandsharethi(),
                                  ),
                                  Positioned(
                                    left: 29.0009765625,
                                    top: 351.10772705078125,
                                    right: null,
                                    bottom: null,
                                    width: 316.998779296875,
                                    height: 237.3577117919922,
                                    child: GeneratedRectangle368Widget74(),
                                  ),
                                  Positioned(
                                    left: 29.0009765625,
                                    top: 218.202880859375,
                                    right: null,
                                    bottom: null,
                                    width: 88.0,
                                    height: 24.0,
                                    child: GeneratedCollectionsWidget(),
                                  ),
                                  Positioned(
                                    left: 29.0009765625,
                                    top: 618.6949462890625,
                                    right: null,
                                    bottom: null,
                                    width: 62.0,
                                    height: 21.0,
                                    child: GeneratedAllBookWidget(),
                                  ),
                                  Positioned(
                                    left: 305.999755859375,
                                    top: 46.4803466796875,
                                    right: null,
                                    bottom: null,
                                    width: 40.0,
                                    height: 40.0,
                                    child: GeneratedEllipse69Widget(),
                                  ),
                                  Positioned(
                                    left: 305.14837646484375,
                                    top: 610.0074462890625,
                                    right: null,
                                    bottom: null,
                                    width: 40.0,
                                    height: 40.0,
                                    child: GeneratedEllipse71Widget(),
                                  ),
                                  Positioned(
                                    left: 316.14837646484375,
                                    top: null,
                                    right: null,
                                    bottom: 1245.9925537109375,
                                    width: 18.0,
                                    height: 18.0,
                                    child: GeneratedIc24sortWidget(),
                                  ),
                                  Positioned(
                                    left: 318.5546875,
                                    top: 58.98046875,
                                    right: null,
                                    bottom: null,
                                    width: 14.890241622924805,
                                    height: 15.0,
                                    child: GeneratedSettingsWidget2(),
                                  ),
                                  Positioned(
                                    left: 326.0,
                                    top: 384.326171875,
                                    right: null,
                                    bottom: null,
                                    width: 276.99884033203125,
                                    height: 124.38690185546875,
                                    child: GeneratedRectangle352Widget(),
                                  ),
                                  Positioned(
                                    left: 336.85009765625,
                                    top: 415.4013671875,
                                    right: null,
                                    bottom: null,
                                    width: 298.6991882324219,
                                    height: 149.36297607421875,
                                    child: GeneratedRectangle355Widget(),
                                  ),
                                  Positioned(
                                    left: 28.5322265625,
                                    top: 274.013671875,
                                    right: null,
                                    bottom: null,
                                    width: 316.998779296875,
                                    height: 315.8452453613281,
                                    child: GeneratedGroup251Widget(),
                                  ),
                                  Positioned(
                                    left: 29.0,
                                    top: 669.5496215820312,
                                    right: null,
                                    bottom: null,
                                    width: 150.0,
                                    height: 242.8297119140625,
                                    child: GeneratedBookWidget4(),
                                  ),
                                  Positioned(
                                    left: 29.0,
                                    top: 940.9089965820312,
                                    right: null,
                                    bottom: null,
                                    width: 150.0,
                                    height: 242.8297119140625,
                                    child: GeneratedBookWidget5(),
                                  ),
                                  Positioned(
                                    left: 29.0,
                                    top: 1212.268310546875,
                                    right: null,
                                    bottom: null,
                                    width: 150.0,
                                    height: 242.8297119140625,
                                    child: GeneratedBookWidget6(),
                                  ),
                                  Positioned(
                                    left: 29.0,
                                    top: 1483.6280517578125,
                                    right: null,
                                    bottom: null,
                                    width: 150.0,
                                    height: 242.8297119140625,
                                    child: GeneratedBookWidget7(),
                                  ),
                                  Positioned(
                                    left: 29.0,
                                    top: 1754.98779296875,
                                    right: null,
                                    bottom: null,
                                    width: 150.0,
                                    height: 242.8297119140625,
                                    child: GeneratedBookWidget8(),
                                  ),
                                  Positioned(
                                    left: 195.531005859375,
                                    top: 669.5496215820312,
                                    right: null,
                                    bottom: null,
                                    width: 150.0,
                                    height: 242.8297119140625,
                                    child: GeneratedBookWidget9(),
                                  ),
                                  Positioned(
                                    left: 195.531005859375,
                                    top: 940.9089965820312,
                                    right: null,
                                    bottom: null,
                                    width: 150.0,
                                    height: 242.8297119140625,
                                    child: GeneratedBookWidget10(),
                                  ),
                                  Positioned(
                                    left: 195.531005859375,
                                    top: 1212.268310546875,
                                    right: null,
                                    bottom: null,
                                    width: 150.0,
                                    height: 242.8297119140625,
                                    child: GeneratedBookWidget11(),
                                  ),
                                  Positioned(
                                    left: 195.531005859375,
                                    top: 1483.6280517578125,
                                    right: null,
                                    bottom: null,
                                    width: 150.0,
                                    height: 242.8297119140625,
                                    child: GeneratedBookWidget12(),
                                  ),
                                  Positioned(
                                    left: 195.531005859375,
                                    top: 1754.98779296875,
                                    right: null,
                                    bottom: null,
                                    width: 150.0,
                                    height: 242.8297119140625,
                                    child: GeneratedBookWidget13(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: null,
              top: null,
              right: null,
              bottom: 35.154083251953125,
              width: 315.0,
              height: 63.017059326171875,
              child: GeneratedBottom_barWidget3(),
            )
          ]),
    ));
  }
}
