import 'package:flutter/material.dart';
import 'package:flutterapp/test1app/generatedpopupdowloadwidget/generated/GeneratedRectangle392Widget10.dart';
import 'package:flutterapp/test1app/generatedpopupdowloadwidget/generated/GeneratedDowloadCompletedWidget1.dart';
import 'package:flutterapp/test1app/generatedpopupdowloadwidget/generated/GeneratedGrabaCoffeeandstartreadingitWidget1.dart';
import 'package:flutterapp/test1app/generatedpopupdowloadwidget/generated/GeneratedIcon3d__571Widget.dart';
import 'package:flutterapp/test1app/generatedpopupdowloadwidget/generated/GeneratedRectangle360Widget4.dart';
import 'package:flutterapp/test1app/generatedpopupdowloadwidget/generated/GeneratedGroup357Widget4.dart';

/* Frame popup dowload 
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPopupdowloadWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 820.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Image.asset(
                  "assets/images/67f8e51657c66919334759d2ab50821e86c501bf.png",
                  color: null,
                  fit: BoxFit.cover,
                  width: 375.0,
                  height: 820.0,
                  colorBlendMode: BlendMode.dstATop,
                ),
              ),
              Positioned(
                left: 0.0009765625,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 820.0,
                child: GeneratedRectangle392Widget10(),
              ),
              Positioned(
                left: 49.3994140625,
                top: 169.04847717285156,
                right: null,
                bottom: null,
                width: 276.1983337402344,
                height: 316.78363037109375,
                child: GeneratedRectangle360Widget4(),
              ),
              Positioned(
                left: 84.31890869140625,
                top: 200.58444213867188,
                right: null,
                bottom: null,
                width: 206.3641357421875,
                height: 206.3641357421875,
                child: GeneratedGroup357Widget4(),
              ),
              Positioned(
                left: 113.0009765625,
                top: 427.0499267578125,
                right: null,
                bottom: null,
                width: 151.0,
                height: 21.0,
                child: GeneratedDowloadCompletedWidget1(),
              ),
              Positioned(
                left: 98.0,
                top: 448.6773681640625,
                right: null,
                bottom: null,
                width: 180.0,
                height: 20.0,
                child: GeneratedGrabaCoffeeandstartreadingitWidget1(),
              ),
              Positioned(
                left: 52.24365234375,
                top: 163.2581787109375,
                right: null,
                bottom: null,
                width: 280.15216064453125,
                height: 280.15216064453125,
                child: GeneratedIcon3d__571Widget(),
              )
            ]),
      ),
    ));
  }
}
