import 'package:flutter/material.dart';
import 'package:flutterapp/test1app/generateddonewidget19/generated/GeneratedRectangle34Widget7.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/test1app/generateddonewidget19/generated/GeneratedDoneWidget20.dart';

/* Component Done
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDoneWidget19 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 53.2668571472168,
      height: 18.34760093688965,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height = constraints.maxHeight;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedRectangle34Widget7(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.5256551916065693;

                final double height = constraints.maxHeight * 0.817545577298939;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.28410153494227525,
                      y: constraints.maxHeight * 0.22748480756702036,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedDoneWidget20(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
