import 'package:flutter/material.dart';
import 'package:flutterapp/test1app/generatedchatwidget/generated/GeneratedRectangle399Widget1.dart';
import 'package:flutterapp/test1app/generatedchatwidget/generated/GeneratedEllipse68Widget50.dart';
import 'package:flutterapp/test1app/generatedchatwidget/generated/GeneratedRectangle399Widget.dart';
import 'package:flutterapp/test1app/generatedchatwidget/generated/GeneratedXDWidget.dart';
import 'package:flutterapp/test1app/generatedchatwidget/generated/GeneratedManydesktoppublishingpackagesandwebpageeditorsWidget.dart';
import 'package:flutterapp/test1app/generatedchatwidget/generated/GeneratedBackWidget47.dart';
import 'package:flutterapp/test1app/generatedchatwidget/generated/GeneratedContrarytopopularbeliefLoremIpsumisnotsimplyrandomtextW.dart';
import 'package:flutterapp/test1app/generatedchatwidget/generated/GeneratedEllipse75Widget3.dart';
import 'package:flutterapp/test1app/generatedchatwidget/generated/GeneratedGroup287Widget.dart';
import 'package:flutterapp/test1app/generatedchatwidget/generated/GeneratedIfyouaregoingtouseapassageofLoremIpsumyouneedtobesureth.dart';
import 'package:flutterapp/test1app/generatedchatwidget/generated/GeneratedRectangle398Widget.dart';
import 'package:flutterapp/test1app/generatedchatwidget/generated/GeneratedRectangle373Widget7.dart';
import 'package:flutterapp/test1app/generatedchatwidget/generated/GeneratedAaWidget.dart';
import 'package:flutterapp/test1app/generatedchatwidget/generated/GeneratedEllipse75Widget2.dart';
import 'package:flutterapp/test1app/generatedchatwidget/generated/GeneratedRectangle358Widget23.dart';
import 'package:flutterapp/test1app/generatedchatwidget/generated/GeneratedEllipse69Widget27.dart';
import 'package:flutterapp/test1app/generatedchatwidget/generated/GeneratedJoshuaLomaxWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/test1app/generatedchatwidget/generated/GeneratedRectangle375Widget6.dart';
import 'package:flutterapp/test1app/generatedchatwidget/generated/GeneratedRectangle374Widget11.dart';
import 'package:flutterapp/test1app/generatedchatwidget/generated/GeneratedThestandardchunkofLoremIpsumusedsincethe1500sisreproduc1.dart';
import 'package:flutterapp/test1app/generatedchatwidget/generated/GeneratedHorrororcomicWidget4.dart';
import 'package:flutterapp/test1app/generatedchatwidget/generated/GeneratedRectangle374Widget13.dart';
import 'package:flutterapp/test1app/generatedchatwidget/generated/GeneratedItisalongestablishedfactthatareaderwillbedistractedbyth1.dart';
import 'package:flutterapp/test1app/generatedchatwidget/generated/GeneratedRectangle401Widget.dart';
import 'package:flutterapp/test1app/generatedchatwidget/generated/Generated2053MonWidget.dart';
import 'package:flutterapp/test1app/generatedchatwidget/generated/GeneratedGroup288Widget.dart';
import 'package:flutterapp/test1app/generatedchatwidget/generated/GeneratedEllipse73Widget9.dart';
import 'package:flutterapp/test1app/generatedchatwidget/generated/GeneratedGroup295Widget.dart';
import 'package:flutterapp/test1app/generatedchatwidget/generated/GeneratedRectangle374Widget12.dart';
import 'package:flutterapp/test1app/generatedchatwidget/generated/GeneratedEllipse74Widget8.dart';
import 'package:flutterapp/test1app/generatedchatwidget/generated/GeneratedIc20attachmentWidget.dart';

/* Frame chat
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChatWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 820.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: null,
                      bottom: null,
                      width: 375.0,
                      height: 818.0,
                      child: GeneratedRectangle358Widget23(),
                    ),
                    Positioned(
                      left: 99.1240234375,
                      top: 37.14447021484375,
                      right: null,
                      bottom: null,
                      width: 246.8759765625,
                      height: 66.02729034423828,
                      child: GeneratedGroup295Widget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: null,
                      bottom: null,
                      width: 375.0,
                      height: 100.0,
                      child: GeneratedRectangle401Widget(),
                    ),
                    Positioned(
                      left: 305.828125,
                      top: 46.086181640625,
                      right: null,
                      bottom: null,
                      width: 40.0,
                      height: 40.0,
                      child: GeneratedEllipse69Widget27(),
                    ),
                    Positioned(
                      left: 28.828125,
                      top: 46.086181640625,
                      right: null,
                      bottom: null,
                      width: 40.0,
                      height: 40.0,
                      child: GeneratedEllipse68Widget50(),
                    ),
                    Positioned(
                      left: 135.0,
                      top: 54.72998046875,
                      right: null,
                      bottom: null,
                      width: 107.0,
                      height: 21.0,
                      child: GeneratedJoshuaLomaxWidget(),
                    ),
                    Positioned(
                      left: 29.4384765625,
                      top: 611.5194091796875,
                      right: null,
                      bottom: null,
                      width: 50.5,
                      height: 50.5,
                      child: GeneratedEllipse73Widget9(),
                    ),
                    Positioned(
                      left: 99.1240234375,
                      top: 611.1287841796875,
                      right: null,
                      bottom: null,
                      width: 230.8759765625,
                      height: 54.495826721191406,
                      child: GeneratedRectangle373Widget7(),
                    ),
                    Positioned(
                      left: 113.5458984375,
                      top: 619.2156982421875,
                      right: null,
                      bottom: null,
                      width: 91.0,
                      height: 20.0,
                      child: GeneratedHorrororcomicWidget4(),
                    ),
                    Positioned(
                      left: 29.4384765625,
                      top: 415.7798767089844,
                      right: null,
                      bottom: null,
                      width: 50.5,
                      height: 50.5,
                      child: GeneratedEllipse74Widget8(),
                    ),
                    Positioned(
                      left: 99.1240234375,
                      top: 415.7798767089844,
                      right: null,
                      bottom: null,
                      width: 230.8759765625,
                      height: 88.42533111572266,
                      child: GeneratedRectangle375Widget6(),
                    ),
                    Positioned(
                      left: 113.5458984375,
                      top: 424.0614929199219,
                      right: null,
                      bottom: null,
                      width: 200.31613159179688,
                      height: 75.32528686523438,
                      child:
                          GeneratedItisalongestablishedfactthatareaderwillbedistractedbyth1(),
                    ),
                    Positioned(
                      left: 29.4384765625,
                      top: 319.0669860839844,
                      right: null,
                      bottom: null,
                      width: 50.5,
                      height: 50.5,
                      child: GeneratedEllipse75Widget2(),
                    ),
                    Positioned(
                      left: 99.1240234375,
                      top: 319.0669860839844,
                      right: null,
                      bottom: null,
                      width: 230.8759765625,
                      height: 88.42533111572266,
                      child: GeneratedRectangle399Widget(),
                    ),
                    Positioned(
                      left: 113.5458984375,
                      top: 327.3486022949219,
                      right: null,
                      bottom: null,
                      width: 200.31613159179688,
                      height: 73.82546997070312,
                      child:
                          GeneratedIfyouaregoingtouseapassageofLoremIpsumyouneedtobesureth(),
                    ),
                    Positioned(
                      left: 29.4384765625,
                      top: 193.49612426757812,
                      right: null,
                      bottom: null,
                      width: 50.5,
                      height: 50.5,
                      child: GeneratedEllipse75Widget3(),
                    ),
                    Positioned(
                      left: 99.1240234375,
                      top: 193.49612426757812,
                      right: null,
                      bottom: null,
                      width: 53.88932418823242,
                      height: 41.28596878051758,
                      child: GeneratedRectangle399Widget1(),
                    ),
                    Positioned(
                      left: 113.5458984375,
                      top: 201.77774047851562,
                      right: null,
                      bottom: null,
                      width: 203.31613159179688,
                      height: 27.89532470703125,
                      child: GeneratedXDWidget(),
                    ),
                    Positioned(
                      left: 346.0,
                      top: 512.4927368164062,
                      right: null,
                      bottom: null,
                      width: 250.8759765625,
                      height: 54.495826721191406,
                      child: GeneratedRectangle374Widget11(),
                    ),
                    Positioned(
                      left: 113.5458984375,
                      top: 518.6400756835938,
                      right: null,
                      bottom: null,
                      width: 219.74560546875,
                      height: 38.0,
                      child:
                          GeneratedContrarytopopularbeliefLoremIpsumisnotsimplyrandomtextW(),
                    ),
                    Positioned(
                      left: 346.0,
                      top: 256.28363037109375,
                      right: null,
                      bottom: null,
                      width: 250.8759765625,
                      height: 54.495826721191406,
                      child: GeneratedRectangle374Widget12(),
                    ),
                    Positioned(
                      left: 113.5458984375,
                      top: 262.43096923828125,
                      right: null,
                      bottom: null,
                      width: 219.74560546875,
                      height: 38.0,
                      child:
                          GeneratedManydesktoppublishingpackagesandwebpageeditorsWidget(),
                    ),
                    Positioned(
                      left: 346.0,
                      top: 115.1812744140625,
                      right: null,
                      bottom: null,
                      width: 250.8759765625,
                      height: 70.02729034423828,
                      child: GeneratedRectangle374Widget13(),
                    ),
                    Positioned(
                      left: 113.5458984375,
                      top: 121.32861328125,
                      right: null,
                      bottom: null,
                      width: 219.74560546875,
                      height: 56.0,
                      child:
                          GeneratedThestandardchunkofLoremIpsumusedsincethe1500sisreproduc1(),
                    ),
                    Positioned(
                      left: 156.0,
                      top: 579.05859375,
                      right: null,
                      bottom: null,
                      width: 61.0,
                      height: 20.0,
                      child: Generated2053MonWidget(),
                    ),
                    Positioned(
                      left: 43.0,
                      top: 755.0,
                      right: null,
                      bottom: null,
                      width: 17.0,
                      height: 18.0,
                      child: GeneratedIc20attachmentWidget(),
                    ),
                    Positioned(
                      left: 43.0,
                      top: 58.980224609375,
                      right: null,
                      bottom: null,
                      width: 8.892169952392578,
                      height: 15.0,
                      child: GeneratedBackWidget47(),
                    ),
                    Positioned(
                      left: null,
                      top: null,
                      right: null,
                      bottom: 32.0,
                      width: 216.0,
                      height: 45.0,
                      child: TransformHelper.translate(
                          x: 0.50,
                          y: 0.00,
                          z: 0,
                          child: GeneratedRectangle398Widget()),
                    ),
                    Positioned(
                      left: null,
                      top: null,
                      right: null,
                      bottom: 43.04833984375,
                      width: 22.0,
                      height: 21.0,
                      child: TransformHelper.translate(
                          x: -79.68, y: 0.00, z: 0, child: GeneratedAaWidget()),
                    )
                  ]),
            ),
            Positioned(
              left: 300.08416748046875,
              top: 742.8014526367188,
              right: null,
              bottom: null,
              width: 45.82780456542969,
              height: 45.82530975341797,
              child: GeneratedGroup287Widget(),
            ),
            Positioned(
              left: null,
              top: null,
              right: null,
              bottom: 31.37323760986328,
              width: 45.82780456542969,
              height: 45.82530975341797,
              child: TransformHelper.translate(
                  x: -135.50, y: 0.00, z: 0, child: GeneratedGroup288Widget()),
            )
          ]),
    ));
  }
}
