import 'package:flutter/material.dart';
import 'package:flutterapp/test1app/generatedsearchwidget11/generated/GeneratedEllipse68Widget54.dart';
import 'package:flutterapp/test1app/generatedsearchwidget11/generated/GeneratedRectangle390Widget29.dart';
import 'package:flutterapp/test1app/generatedsearchwidget11/generated/GeneratedBackWidget51.dart';
import 'package:flutterapp/test1app/generatedsearchwidget11/generated/GeneratedRectangle392Widget17.dart';
import 'package:flutterapp/test1app/generatedsearchwidget11/generated/GeneratedComponent12Widget2.dart';
import 'package:flutterapp/test1app/generatedsearchwidget11/generated/GeneratedComponent10Widget4.dart';
import 'package:flutterapp/test1app/generatedsearchwidget11/generated/GeneratedTrendingWidget3.dart';
import 'package:flutterapp/test1app/generatedsearchwidget11/generated/GeneratedGroup336Widget7.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/test1app/generatedsearchwidget11/generated/GeneratedComponent11Widget3.dart';

/* Frame Search
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchWidget11 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 820.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height = constraints.maxHeight;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.0000026041666666666666,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle390Widget29(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0009765625,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 820.0,
                child: GeneratedRectangle392Widget17(),
              ),
              Positioned(
                left: 28.7822265625,
                top: 46.08642578125,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse68Widget54(),
              ),
              Positioned(
                left: 44.0,
                top: 58.98046875,
                right: null,
                bottom: null,
                width: 8.892169952392578,
                height: 15.0,
                child: GeneratedBackWidget51(),
              ),
              Positioned(
                left: 80.06267547607422,
                top: 46.08642578125,
                right: null,
                bottom: null,
                width: 265.93731689453125,
                height: 40.0,
                child: GeneratedGroup336Widget7(),
              ),
              Positioned(
                left: 25.0,
                top: 130.61279296875,
                right: null,
                bottom: null,
                width: 70.0,
                height: 24.0,
                child: GeneratedTrendingWidget3(),
              ),
              Positioned(
                left: 25.0,
                top: 438.414306640625,
                right: null,
                bottom: null,
                width: 325.5859680175781,
                height: 110.0,
                child: GeneratedComponent10Widget4(),
              ),
              Positioned(
                left: 25.0,
                top: 179.03857421875,
                right: null,
                bottom: null,
                width: 325.5859680175781,
                height: 110.0,
                child: GeneratedComponent11Widget3(),
              ),
              Positioned(
                left: 25.0,
                top: 308.726318359375,
                right: null,
                bottom: null,
                width: 325.5859680175781,
                height: 110.0,
                child: GeneratedComponent12Widget2(),
              )
            ]),
      ),
    ));
  }
}
