import 'package:flutter/material.dart';
import 'package:flutterapp/test1app/generatedinvitefriend_2widget/generated/GeneratedEllipse68Widget46.dart';
import 'package:flutterapp/test1app/generatedinvitefriend_2widget/generated/GeneratedEllipse74Widget2.dart';
import 'package:flutterapp/test1app/generatedinvitefriend_2widget/generated/GeneratedGroup278Widget.dart';
import 'package:flutterapp/test1app/generatedinvitefriend_2widget/generated/GeneratedImage4Widget.dart';
import 'package:flutterapp/test1app/generatedinvitefriend_2widget/generated/GeneratedEllipse66Widget15.dart';
import 'package:flutterapp/test1app/generatedinvitefriend_2widget/generated/GeneratedMessageWidget3.dart';
import 'package:flutterapp/test1app/generatedinvitefriend_2widget/generated/GeneratedEllipse73Widget3.dart';
import 'package:flutterapp/test1app/generatedinvitefriend_2widget/generated/GeneratedEllipse72Widget1.dart';
import 'package:flutterapp/test1app/generatedinvitefriend_2widget/generated/GeneratedImage3Widget4.dart';
import 'package:flutterapp/test1app/generatedinvitefriend_2widget/generated/GeneratedImage2Widget4.dart';
import 'package:flutterapp/test1app/generatedinvitefriend_2widget/generated/GeneratedPatriciaWilliamsWidget.dart';
import 'package:flutterapp/test1app/generatedinvitefriend_2widget/generated/GeneratedMoreFriendsMoreFunsWidget.dart';
import 'package:flutterapp/test1app/generatedinvitefriend_2widget/generated/GeneratedLindaLeeWidget.dart';
import 'package:flutterapp/test1app/generatedinvitefriend_2widget/generated/GeneratedMarkSmithWidget.dart';
import 'package:flutterapp/test1app/generatedinvitefriend_2widget/generated/GeneratedGroup279Widget.dart';
import 'package:flutterapp/test1app/generatedinvitefriend_2widget/generated/GeneratedBackWidget43.dart';
import 'package:flutterapp/test1app/generatedinvitefriend_2widget/generated/GeneratedImage5Widget.dart';
import 'package:flutterapp/test1app/generatedinvitefriend_2widget/generated/GeneratedMonaChalabiWidget.dart';
import 'package:flutterapp/test1app/generatedinvitefriend_2widget/generated/GeneratedEllipse71Widget3.dart';
import 'package:flutterapp/test1app/generatedinvitefriend_2widget/generated/GeneratedImage1Widget6.dart';
import 'package:flutterapp/test1app/generatedinvitefriend_2widget/generated/GeneratedRectangle358Widget19.dart';
import 'package:flutterapp/test1app/generatedinvitefriend_2widget/generated/GeneratedEllipse70Widget2.dart';
import 'package:flutterapp/test1app/generatedinvitefriend_2widget/generated/GeneratedGroup281Widget.dart';
import 'package:flutterapp/test1app/generatedinvitefriend_2widget/generated/GeneratedMaryJohnsonWidget.dart';
import 'package:flutterapp/test1app/generatedinvitefriend_2widget/generated/GeneratedGroup280Widget.dart';

/* Frame invite friend_2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInvitefriend_2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 820.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 818.0,
                child: GeneratedRectangle358Widget19(),
              ),
              Positioned(
                left: 29.0003662109375,
                top: 720.0,
                right: null,
                bottom: null,
                width: 316.999267578125,
                height: 64.56744384765625,
                child: GeneratedGroup281Widget(),
              ),
              Positioned(
                left: 305.828125,
                top: 46.086212158203125,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse66Widget15(),
              ),
              Positioned(
                left: 316.828125,
                top: 58.94239807128906,
                right: null,
                bottom: null,
                width: 18.0,
                height: 18.0,
                child: GeneratedMessageWidget3(),
              ),
              Positioned(
                left: 56.00048828125,
                top: 214.8787078857422,
                right: null,
                bottom: null,
                width: 265.0,
                height: 33.0,
                child: GeneratedMoreFriendsMoreFunsWidget(),
              ),
              Positioned(
                left: 101.00048828125,
                top: 288.4300842285156,
                right: null,
                bottom: null,
                width: 99.0,
                height: 22.0,
                child: GeneratedMonaChalabiWidget(),
              ),
              Positioned(
                left: 101.37646484375,
                top: 378.5318908691406,
                right: null,
                bottom: null,
                width: 77.0,
                height: 22.0,
                child: GeneratedMarkSmithWidget(),
              ),
              Positioned(
                left: 99.00048828125,
                top: 468.6336975097656,
                right: null,
                bottom: null,
                width: 112.0,
                height: 22.0,
                child: GeneratedPatriciaWilliamsWidget(),
              ),
              Positioned(
                left: 99.00048828125,
                top: 558.7354736328125,
                right: null,
                bottom: null,
                width: 97.0,
                height: 22.0,
                child: GeneratedMaryJohnsonWidget(),
              ),
              Positioned(
                left: 99.00048828125,
                top: 648.8372802734375,
                right: null,
                bottom: null,
                width: 67.0,
                height: 22.0,
                child: GeneratedLindaLeeWidget(),
              ),
              Positioned(
                left: 38.828125,
                top: 121.06771850585938,
                right: null,
                bottom: null,
                width: 76.16944885253906,
                height: 76.16944885253906,
                child: GeneratedGroup278Widget(),
              ),
              Positioned(
                left: 259.65869140625,
                top: 121.06771850585938,
                right: null,
                bottom: null,
                width: 76.16944885253906,
                height: 76.16944885253906,
                child: GeneratedGroup280Widget(),
              ),
              Positioned(
                left: 128.1142578125,
                top: 89.76614379882812,
                right: null,
                bottom: null,
                width: 118.77255249023438,
                height: 118.77255249023438,
                child: GeneratedGroup279Widget(),
              ),
              Positioned(
                left: 28.94873046875,
                top: 273.1821594238281,
                right: null,
                bottom: null,
                width: 50.495826721191406,
                height: 50.495826721191406,
                child: GeneratedEllipse70Widget2(),
              ),
              Positioned(
                left: 28.94873046875,
                top: 363.2839660644531,
                right: null,
                bottom: null,
                width: 50.495826721191406,
                height: 50.495826721191406,
                child: GeneratedEllipse71Widget3(),
              ),
              Positioned(
                left: 28.94873046875,
                top: 453.38580322265625,
                right: null,
                bottom: null,
                width: 50.495826721191406,
                height: 50.495826721191406,
                child: GeneratedEllipse72Widget1(),
              ),
              Positioned(
                left: 28.94873046875,
                top: 543.6389770507812,
                right: null,
                bottom: null,
                width: 50.495826721191406,
                height: 50.495826721191406,
                child: GeneratedEllipse73Widget3(),
              ),
              Positioned(
                left: 28.94873046875,
                top: 633.8921508789062,
                right: null,
                bottom: null,
                width: 50.495826721191406,
                height: 50.495826721191406,
                child: GeneratedEllipse74Widget2(),
              ),
              Positioned(
                left: 28.828125,
                top: 46.086181640625,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse68Widget46(),
              ),
              Positioned(
                left: 305.82830810546875,
                top: 278.1080017089844,
                right: null,
                bottom: null,
                width: 40.64314651489258,
                height: 40.64314651489258,
                child: GeneratedImage1Widget6(),
              ),
              Positioned(
                left: 305.82830810546875,
                top: 368.2100830078125,
                right: null,
                bottom: null,
                width: 40.64314651489258,
                height: 40.64314651489258,
                child: GeneratedImage2Widget4(),
              ),
              Positioned(
                left: 305.82830810546875,
                top: 458.3121337890625,
                right: null,
                bottom: null,
                width: 40.64314651489258,
                height: 40.64314651489258,
                child: GeneratedImage3Widget4(),
              ),
              Positioned(
                left: 305.82830810546875,
                top: 548.4141845703125,
                right: null,
                bottom: null,
                width: 40.64314651489258,
                height: 40.64314651489258,
                child: GeneratedImage4Widget(),
              ),
              Positioned(
                left: 305.82830810546875,
                top: 638.5162353515625,
                right: null,
                bottom: null,
                width: 40.64314651489258,
                height: 40.64314651489258,
                child: GeneratedImage5Widget(),
              ),
              Positioned(
                left: 43.0,
                top: 58.980224609375,
                right: null,
                bottom: null,
                width: 8.892169952392578,
                height: 15.0,
                child: GeneratedBackWidget43(),
              )
            ]),
      ),
    ));
  }
}
