import 'package:flutter/material.dart';
import 'package:flutterapp/test1app/generatedbook_detailwidget/generated/Generated208Widget.dart';
import 'package:flutterapp/test1app/generatedbook_detailwidget/generated/GeneratedLogoModernismWidget.dart';
import 'package:flutterapp/test1app/generatedbook_detailwidget/generated/GeneratedRectangle300Widget6.dart';
import 'package:flutterapp/test1app/generatedbook_detailwidget/generated/GeneratedButImustexplaintoyouhowallthismistakenideaofdenouncingp6.dart';
import 'package:flutterapp/test1app/generatedbook_detailwidget/generated/GeneratedRectangle301Widget.dart';
import 'package:flutterapp/test1app/generatedbook_detailwidget/generated/GeneratedRectangle299Widget.dart';
import 'package:flutterapp/test1app/generatedbook_detailwidget/generated/GeneratedRectangle298Widget1.dart';

/* Frame Book_detail
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBook_detailWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 820.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 818.0,
                child: GeneratedRectangle298Widget1(),
              ),
              Positioned(
                left: 21.89191436767578,
                top: 22.0,
                right: null,
                bottom: null,
                width: 331.2161560058594,
                height: 735.591064453125,
                child: GeneratedRectangle299Widget(),
              ),
              Positioned(
                left: 11.415168762207031,
                top: 22.0,
                right: null,
                bottom: null,
                width: 352.1696472167969,
                height: 724.9304809570312,
                child: GeneratedRectangle301Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 818.0,
                child: GeneratedRectangle300Widget6(),
              ),
              Positioned(
                left: 25.0,
                top: 102.91785430908203,
                right: null,
                bottom: null,
                width: 327.0,
                height: 687.4945678710938,
                child:
                    GeneratedButImustexplaintoyouhowallthismistakenideaofdenouncingp6(),
              ),
              Positioned(
                left: 127.0,
                top: 52.765625,
                right: null,
                bottom: null,
                width: 123.0,
                height: 23.0,
                child: GeneratedLogoModernismWidget(),
              ),
              Positioned(
                left: 174.5,
                top: 757.591064453125,
                right: null,
                bottom: null,
                width: 31.0,
                height: 26.0,
                child: Generated208Widget(),
              )
            ]),
      ),
    ));
  }
}
