import 'package:flutter/material.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget6/generated/GeneratedRectangle373Widget5.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget6/generated/GeneratedUntitled12Widget1.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget6/generated/GeneratedBackWidget36.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget6/generated/GeneratedRectangle372Widget4.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget6/generated/GeneratedAddacomentWidget.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget6/generated/Generated412Widget9.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget6/generated/GeneratedReadsWidget9.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget6/generated/GeneratedSmilingfacewithhornsWidget.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget6/generated/GeneratedItemstatusBarsdarkWidget9.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget6/generated/GeneratedUntitled11Widget.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget6/generated/Generated156Widget16.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget6/generated/GeneratedGroup164Widget9.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget6/generated/GeneratedMouthWidget.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget6/generated/GeneratedPartyingfaceWidget.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget6/generated/GeneratedKissmarkWidget.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget6/generated/GeneratedRectangle328Widget11.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget6/generated/GeneratedExplodingheadWidget.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget6/generated/Generated50Widget13.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget6/generated/GeneratedRatingWidget9.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget6/generated/GeneratedReviewWidget9.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget6/generated/GeneratedGrinningfaceWidget.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget6/generated/GeneratedGroup165Widget2.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget6/generated/GeneratedAtveroeosetaccusamusetiustoodiodignissimosducimusquibla8.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget6/generated/GeneratedBookcoverWidget106.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget6/generated/GeneratedRectangle2Widget8.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget6/generated/GeneratedRectangle32Widget22.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget6/generated/GeneratedSmilingfacewithsunglassesWidget.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget6/generated/GeneratedRateWidget.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget6/generated/GeneratedPostWidget.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget6/generated/GeneratedEllipse36Widget1.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget6/generated/GeneratedEllipse68Widget39.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget6/generated/GeneratedShareWidget18.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget6/generated/GeneratedRectangle329Widget8.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget6/generated/GeneratedGroup106Widget8.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget6/generated/GeneratedEllipse66Widget10.dart';

/* Frame Book review
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBookreviewWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 820.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 236, 240, 245),
                ),
              ),
              Positioned(
                left: -69.4482421875,
                top: -142.09051513671875,
                right: null,
                bottom: null,
                width: 513.8966674804688,
                height: 661.0578002929688,
                child: GeneratedRectangle32Widget22(),
              ),
              Positioned(
                left: -69.4482421875,
                top: -142.09051513671875,
                right: null,
                bottom: null,
                width: 513.8966674804688,
                height: 661.0578002929688,
                child: GeneratedRectangle373Widget5(),
              ),
              Positioned(
                left: 103.4283447265625,
                top: 55.392578125,
                right: null,
                bottom: null,
                width: 168.1433868408203,
                height: 240.3837127685547,
                child: GeneratedBookcoverWidget106(),
              ),
              Positioned(
                left: 125.06280517578125,
                top: 298.97802734375,
                right: null,
                bottom: null,
                width: 125.0,
                height: 42.299072265625,
                child: GeneratedGroup165Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.9999982096354166;

                  final double height =
                      constraints.maxHeight * 0.23990675763386052;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.0000013020833333333333,
                        y: constraints.maxHeight * 0.4273309847203697,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle2Widget8(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 421.5306091308594,
                right: null,
                bottom: null,
                width: 375.0,
                height: 392.4694519042969,
                child: GeneratedRectangle328Widget11(),
              ),
              Positioned(
                left: 29.00048828125,
                top: 507.96728515625,
                right: null,
                bottom: null,
                width: 81.0,
                height: 22.0,
                child: GeneratedGroup106Widget8(),
              ),
              Positioned(
                left: 29.00048828125,
                top: 538.802490234375,
                right: null,
                bottom: null,
                width: 327.0,
                height: 192.19744873046875,
                child:
                    GeneratedAtveroeosetaccusamusetiustoodiodignissimosducimusquibla8(),
              ),
              Positioned(
                left: 29.00048828125,
                top: 445.934814453125,
                right: null,
                bottom: null,
                width: 104.0,
                height: 43.89404296875,
                child: GeneratedGroup164Widget9(),
              ),
              Positioned(
                left: 173.0,
                top: 368.1765441894531,
                right: null,
                bottom: null,
                width: 34.0,
                height: 18.0,
                child: GeneratedRatingWidget9(),
              ),
              Positioned(
                left: 0.0,
                top: -1776.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -5.922666666666666,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedItemstatusBarsdarkWidget9(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 85.484375,
                top: 368.1765441894531,
                right: null,
                bottom: null,
                width: 33.0,
                height: 18.0,
                child: GeneratedReadsWidget9(),
              ),
              Positioned(
                left: 256.015625,
                top: 368.1765441894531,
                right: null,
                bottom: null,
                width: 37.0,
                height: 18.0,
                child: GeneratedReviewWidget9(),
              ),
              Positioned(
                left: 176.0,
                top: 380.1765441894531,
                right: null,
                bottom: null,
                width: 28.0,
                height: 27.0,
                child: Generated50Widget13(),
              ),
              Positioned(
                left: 83.98388671875,
                top: 380.1765441894531,
                right: null,
                bottom: null,
                width: 32.0,
                height: 27.0,
                child: Generated412Widget9(),
              ),
              Positioned(
                left: 258.515625,
                top: 380.1765441894531,
                right: null,
                bottom: null,
                width: 32.0,
                height: 27.0,
                child: Generated156Widget16(),
              ),
              Positioned(
                left: 0.0,
                top: 347.847412109375,
                right: null,
                bottom: null,
                width: 374.99981689453125,
                height: 466.116455078125,
                child: GeneratedRectangle329Widget8(),
              ),
              Positioned(
                left: 75.02400207519531,
                top: 368.287353515625,
                right: null,
                bottom: null,
                width: 224.95162963867188,
                height: 29.56910514831543,
                child: GeneratedRateWidget(),
              ),
              Positioned(
                left: 29.0625,
                top: 432.328857421875,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedEllipse36Widget1(),
              ),
              Positioned(
                left: 99.0625,
                top: 432.328857421875,
                right: null,
                bottom: null,
                width: 247.0,
                height: 50.0,
                child: GeneratedRectangle372Widget4(),
              ),
              Positioned(
                left: 113.484375,
                top: 443.328857421875,
                right: null,
                bottom: null,
                width: 219.32080078125,
                height: 29.197063446044922,
                child: GeneratedAddacomentWidget(),
              ),
              Positioned(
                left: 299.9819030761719,
                top: 442.927490234375,
                right: null,
                bottom: null,
                width: 38.0,
                height: 24.0,
                child: GeneratedPostWidget(),
              ),
              Positioned(
                left: -1.8189894035458565e-12,
                top: 498.1934509277344,
                right: null,
                bottom: null,
                width: 375.0,
                height: 315.3861999511719,
                child: GeneratedUntitled11Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 547.0531616210938,
                right: null,
                bottom: null,
                width: 375.0,
                height: 272.94683837890625,
                child: GeneratedUntitled12Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.06933333333333333;

                  final double height =
                      constraints.maxHeight * 0.033169481230945125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.07625260416666667,
                        y: constraints.maxHeight * 0.6208772240615472,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGrinningfaceWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.072;

                  final double height =
                      constraints.maxHeight * 0.033169481230945125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8495859375,
                        y: constraints.maxHeight * 0.6208772240615472,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedSmilingfacewithsunglassesWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.072;

                  final double height =
                      constraints.maxHeight * 0.033169481230945125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.33491927083333334,
                        y: constraints.maxHeight * 0.6208772240615472,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedPartyingfaceWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.072;

                  final double height =
                      constraints.maxHeight * 0.033169481230945125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.20691927083333334,
                        y: constraints.maxHeight * 0.6208772240615472,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedExplodingheadWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.072;

                  final double height =
                      constraints.maxHeight * 0.033169481230945125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5935859375,
                        y: constraints.maxHeight * 0.6208772240615472,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedSmilingfacewithhornsWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.07466666666666667;

                  final double height =
                      constraints.maxHeight * 0.033169481230945125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.46291927083333334,
                        y: constraints.maxHeight * 0.6208772240615472,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedMouthWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.06933333333333333;

                  final double height =
                      constraints.maxHeight * 0.033169481230945125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.7242526041666667,
                        y: constraints.maxHeight * 0.6208772240615472,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedKissmarkWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 28.5947265625,
                top: 46.480255126953125,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse68Widget39(),
              ),
              Positioned(
                left: 44.0,
                top: 58.980224609375,
                right: null,
                bottom: null,
                width: 8.892169952392578,
                height: 15.0,
                child: GeneratedBackWidget36(),
              ),
              Positioned(
                left: 305.828125,
                top: 46.08642578125,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse66Widget10(),
              ),
              Positioned(
                left: 317.0,
                top: 58.58642578125,
                right: null,
                bottom: null,
                width: 15.0,
                height: 15.0,
                child: GeneratedShareWidget18(),
              )
            ]),
      ),
    ));
  }
}
