import 'package:flutter/material.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget2/generated/GeneratedBookWidget30.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget2/generated/GeneratedSettingsWidget11.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget2/generated/GeneratedGroup251Widget10.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget2/generated/GeneratedBookWidget27.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget2/generated/GeneratedBookWidget28.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget2/generated/GeneratedCollectionsWidget14.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget2/generated/GeneratedBookWidget34.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget2/generated/GeneratedEllipse71Widget9.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget2/generated/GeneratedBookWidget33.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget2/generated/GeneratedRectangle352Widget5.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget2/generated/GeneratedGroup33Widget141.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget2/generated/GeneratedIc24sortWidget1.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget2/generated/GeneratedBookWidget26.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget2/generated/GeneratedBackgroudWidget13.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget2/generated/GeneratedEllipse69Widget31.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget2/generated/GeneratedBookWidget32.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget2/generated/GeneratedRectangle355Widget5.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget2/generated/GeneratedBookWidget29.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget2/generated/GeneratedBookWidget35.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget2/generated/GeneratedBookWidget31.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget2/generated/GeneratedAllBookWidget1.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget2/generated/GeneratedSynthesizefavoritebooksyourwayEveryonecanseeandsharethi5.dart';
import 'package:flutterapp/test1app/generatedlibrarywidget2/generated/GeneratedBottom_barWidget7.dart';

/* Frame Library
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLibraryWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 3629.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 375.0,
                            height: 1885.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 236, 240, 245),
                                    ),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 3629.0,
                                    child: GeneratedBackgroudWidget13(),
                                  ),
                                  Positioned(
                                    left: 29.0,
                                    top: 102.762939453125,
                                    right: null,
                                    bottom: null,
                                    width: 115.0,
                                    height: 42.0,
                                    child: GeneratedGroup33Widget141(),
                                  ),
                                  Positioned(
                                    left: 29.0,
                                    top: 153.053466796875,
                                    right: null,
                                    bottom: null,
                                    width: 319.0001220703125,
                                    height: 38.0,
                                    child:
                                        GeneratedSynthesizefavoritebooksyourwayEveryonecanseeandsharethi5(),
                                  ),
                                  Positioned(
                                    left: 29.0009765625,
                                    top: 218.202880859375,
                                    right: null,
                                    bottom: null,
                                    width: 88.0,
                                    height: 24.0,
                                    child: GeneratedCollectionsWidget14(),
                                  ),
                                  Positioned(
                                    left: 29.0009765625,
                                    top: 618.6949462890625,
                                    right: null,
                                    bottom: null,
                                    width: 62.0,
                                    height: 21.0,
                                    child: GeneratedAllBookWidget1(),
                                  ),
                                  Positioned(
                                    left: 305.999755859375,
                                    top: 46.4803466796875,
                                    right: null,
                                    bottom: null,
                                    width: 40.0,
                                    height: 40.0,
                                    child: GeneratedEllipse69Widget31(),
                                  ),
                                  Positioned(
                                    left: 305.14837646484375,
                                    top: 610.0074462890625,
                                    right: null,
                                    bottom: null,
                                    width: 40.0,
                                    height: 40.0,
                                    child: GeneratedEllipse71Widget9(),
                                  ),
                                  Positioned(
                                    left: 316.14837646484375,
                                    top: null,
                                    right: null,
                                    bottom: 1245.9925537109375,
                                    width: 18.0,
                                    height: 18.0,
                                    child: GeneratedIc24sortWidget1(),
                                  ),
                                  Positioned(
                                    left: 318.5546875,
                                    top: 58.98046875,
                                    right: null,
                                    bottom: null,
                                    width: 14.890241622924805,
                                    height: 15.0,
                                    child: GeneratedSettingsWidget11(),
                                  ),
                                  Positioned(
                                    left: 326.0,
                                    top: 384.326171875,
                                    right: null,
                                    bottom: null,
                                    width: 276.99884033203125,
                                    height: 124.38690185546875,
                                    child: GeneratedRectangle352Widget5(),
                                  ),
                                  Positioned(
                                    left: 336.85009765625,
                                    top: 415.4013671875,
                                    right: null,
                                    bottom: null,
                                    width: 298.6991882324219,
                                    height: 149.36297607421875,
                                    child: GeneratedRectangle355Widget5(),
                                  ),
                                  Positioned(
                                    left: 29.00082778930664,
                                    top: 274.013671875,
                                    right: null,
                                    bottom: null,
                                    width: 316.998779296875,
                                    height: 315.8452453613281,
                                    child: GeneratedGroup251Widget10(),
                                  ),
                                  Positioned(
                                    left: 29.0,
                                    top: 669.5496215820312,
                                    right: null,
                                    bottom: null,
                                    width: 150.0,
                                    height: 242.8297119140625,
                                    child: GeneratedBookWidget26(),
                                  ),
                                  Positioned(
                                    left: 29.0,
                                    top: 940.9089965820312,
                                    right: null,
                                    bottom: null,
                                    width: 150.0,
                                    height: 242.8297119140625,
                                    child: GeneratedBookWidget27(),
                                  ),
                                  Positioned(
                                    left: 29.0,
                                    top: 1212.268310546875,
                                    right: null,
                                    bottom: null,
                                    width: 150.0,
                                    height: 242.8297119140625,
                                    child: GeneratedBookWidget28(),
                                  ),
                                  Positioned(
                                    left: 29.0,
                                    top: 1483.6280517578125,
                                    right: null,
                                    bottom: null,
                                    width: 150.0,
                                    height: 242.8297119140625,
                                    child: GeneratedBookWidget29(),
                                  ),
                                  Positioned(
                                    left: 29.0,
                                    top: 1754.98779296875,
                                    right: null,
                                    bottom: null,
                                    width: 150.0,
                                    height: 242.8297119140625,
                                    child: GeneratedBookWidget30(),
                                  ),
                                  Positioned(
                                    left: 195.531005859375,
                                    top: 669.5496215820312,
                                    right: null,
                                    bottom: null,
                                    width: 150.0,
                                    height: 242.8297119140625,
                                    child: GeneratedBookWidget31(),
                                  ),
                                  Positioned(
                                    left: 195.531005859375,
                                    top: 940.9089965820312,
                                    right: null,
                                    bottom: null,
                                    width: 150.0,
                                    height: 242.8297119140625,
                                    child: GeneratedBookWidget32(),
                                  ),
                                  Positioned(
                                    left: 195.531005859375,
                                    top: 1212.268310546875,
                                    right: null,
                                    bottom: null,
                                    width: 150.0,
                                    height: 242.8297119140625,
                                    child: GeneratedBookWidget33(),
                                  ),
                                  Positioned(
                                    left: 195.531005859375,
                                    top: 1483.6280517578125,
                                    right: null,
                                    bottom: null,
                                    width: 150.0,
                                    height: 242.8297119140625,
                                    child: GeneratedBookWidget34(),
                                  ),
                                  Positioned(
                                    left: 195.531005859375,
                                    top: 1754.98779296875,
                                    right: null,
                                    bottom: null,
                                    width: 150.0,
                                    height: 242.8297119140625,
                                    child: GeneratedBookWidget35(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: null,
              top: null,
              right: null,
              bottom: 35.405303955078125,
              width: 315.0,
              height: 63.017059326171875,
              child: GeneratedBottom_barWidget7(),
            )
          ]),
    ));
  }
}
