import 'package:flutter/material.dart';
import 'package:flutterapp/test1app/generatedmembershipwidget/generated/GeneratedVectorWidget343.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/test1app/generatedmembershipwidget/generated/GeneratedEllipse68Widget40.dart';
import 'package:flutterapp/test1app/generatedmembershipwidget/generated/GeneratedGroup348Widget.dart';
import 'package:flutterapp/test1app/generatedmembershipwidget/generated/GeneratedVectorWidget345.dart';
import 'package:flutterapp/test1app/generatedmembershipwidget/generated/GeneratedYouNeedKnowWidget.dart';
import 'package:flutterapp/test1app/generatedmembershipwidget/generated/GeneratedGoPremiumWidget1.dart';
import 'package:flutterapp/test1app/generatedmembershipwidget/generated/Generated4Widget3.dart';
import 'package:flutterapp/test1app/generatedmembershipwidget/generated/GeneratedGroup351Widget.dart';
import 'package:flutterapp/test1app/generatedmembershipwidget/generated/GeneratedVectorWidget344.dart';
import 'package:flutterapp/test1app/generatedmembershipwidget/generated/GeneratedGroup347Widget.dart';
import 'package:flutterapp/test1app/generatedmembershipwidget/generated/GeneratedGroup349Widget1.dart';
import 'package:flutterapp/test1app/generatedmembershipwidget/generated/GeneratedGetallaudiobookspurchasedforeverandlistenagainwhenevery.dart';
import 'package:flutterapp/test1app/generatedmembershipwidget/generated/GeneratedBackWidget37.dart';
import 'package:flutterapp/test1app/generatedmembershipwidget/generated/GeneratedTagsbookWidget.dart';
import 'package:flutterapp/test1app/generatedmembershipwidget/generated/GeneratedGoPremiumWidget2.dart';
import 'package:flutterapp/test1app/generatedmembershipwidget/generated/GeneratedBackgroudWidget5.dart';
import 'package:flutterapp/test1app/generatedmembershipwidget/generated/GeneratedGroup350Widget.dart';
import 'package:flutterapp/test1app/generatedmembershipwidget/generated/GeneratedMembershipWidget1.dart';
import 'package:flutterapp/test1app/generatedmembershipwidget/generated/GeneratedFrame135Widget4.dart';
import 'package:flutterapp/test1app/generatedmembershipwidget/generated/GeneratedFrame134Widget28.dart';
import 'package:flutterapp/test1app/generatedmembershipwidget/generated/GeneratedYougot1tagseachmonthtoselectabuyabooksaidanyvalueWidget.dart';
import 'package:flutterapp/test1app/generatedmembershipwidget/generated/GeneratedGoPremiumWidget.dart';
import 'package:flutterapp/test1app/generatedmembershipwidget/generated/GeneratedYoucancancelyourmembershipatanytimeWidget.dart';

/* Frame Membership
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMembershipWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 820.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 380.0,
                height: 820.0,
                child: GeneratedBackgroudWidget5(),
              ),
              Positioned(
                left: 29.0,
                top: 46.086181640625,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse68Widget40(),
              ),
              Positioned(
                left: 44.0,
                top: 58.980224609375,
                right: null,
                bottom: null,
                width: 8.892169952392578,
                height: 15.0,
                child: GeneratedBackWidget37(),
              ),
              Positioned(
                left: 28.9971923828125,
                top: 173.5458984375,
                right: null,
                bottom: null,
                width: 317.0028381347656,
                height: 174.74066162109375,
                child: GeneratedGroup347Widget(),
              ),
              Positioned(
                left: 271.1904602050781,
                top: 173.918701171875,
                right: null,
                bottom: null,
                width: 40.0,
                height: 92.0,
                child: Generated4Widget3(),
              ),
              Positioned(
                left: 254.25344848632812,
                top: 253.96337890625,
                right: null,
                bottom: null,
                width: 76.0,
                height: 21.0,
                child: GeneratedTagsbookWidget(),
              ),
              Positioned(
                left: 28.9971923828125,
                top: 411.71435546875,
                right: null,
                bottom: null,
                width: 148.0028076171875,
                height: 174.74066162109375,
                child: GeneratedGroup348Widget(),
              ),
              Positioned(
                left: 28.9971923828125,
                top: 598.53759765625,
                right: null,
                bottom: null,
                width: 148.0028076171875,
                height: 45.5312614440918,
                child: GeneratedGroup350Widget(),
              ),
              Positioned(
                left: 197.9971923828125,
                top: 598.53759765625,
                right: null,
                bottom: null,
                width: 148.0028076171875,
                height: 45.5312614440918,
                child: GeneratedGroup351Widget(),
              ),
              Positioned(
                left: 197.99722290039062,
                top: 411.71435546875,
                right: null,
                bottom: null,
                width: 148.0028076171875,
                height: 174.74066162109375,
                child: GeneratedGroup349Widget1(),
              ),
              Positioned(
                left: 234.99853515625,
                top: 557.0,
                right: null,
                bottom: null,
                width: 74.0,
                height: 17.0,
                child: GeneratedFrame134Widget28(),
              ),
              Positioned(
                left: 46.0,
                top: 316.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 17.0,
                child: GeneratedFrame135Widget4(),
              ),
              Positioned(
                left: 29.0,
                top: 102.762939453125,
                right: null,
                bottom: null,
                width: 207.0,
                height: 47.0,
                child: GeneratedMembershipWidget1(),
              ),
              Positioned(
                left: 29.0,
                top: 374.523193359375,
                right: null,
                bottom: null,
                width: 94.0,
                height: 21.0,
                child: GeneratedGoPremiumWidget(),
              ),
              Positioned(
                left: 29.0,
                top: 670.305908203125,
                right: null,
                bottom: null,
                width: 117.0,
                height: 21.0,
                child: GeneratedYouNeedKnowWidget(),
              ),
              Positioned(
                left: 62.49859619140625,
                top: 612.8041381835938,
                right: null,
                bottom: null,
                width: 83.0,
                height: 19.0,
                child: GeneratedGoPremiumWidget1(),
              ),
              Positioned(
                left: 231.49859619140625,
                top: 612.80419921875,
                right: null,
                bottom: null,
                width: 83.0,
                height: 19.0,
                child: GeneratedGoPremiumWidget2(),
              ),
              Positioned(
                left: 52.9244384765625,
                top: 702.53125,
                right: null,
                bottom: null,
                width: 295.0755615234375,
                height: 38.0,
                child:
                    GeneratedYougot1tagseachmonthtoselectabuyabooksaidanyvalueWidget(),
              ),
              Positioned(
                left: 52.9244384765625,
                top: 751.75634765625,
                right: null,
                bottom: null,
                width: 299.431884765625,
                height: 38.0,
                child:
                    GeneratedGetallaudiobookspurchasedforeverandlistenagainwhenevery(),
              ),
              Positioned(
                left: 52.9244384765625,
                top: 800.9814453125,
                right: null,
                bottom: null,
                width: 299.431884765625,
                height: 20.0,
                child: GeneratedYoucancancelyourmembershipatanytimeWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.04097456868489583;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      15.365463256835938;

                  double percentHeight = 0.014929153861069099;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      12.24190616607666;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.07733333333333334,
                        translateY: constraints.maxHeight * 0.8567454268292682,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget343())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.04097456868489583;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      15.365463256835938;

                  double percentHeight = 0.014929153861069099;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      12.24190616607666;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.07733333333333334,
                        translateY: constraints.maxHeight * 0.9177004930449695,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget344())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.04097456868489583;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      15.365463256835938;

                  double percentHeight = 0.014929153861069099;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      12.24190616607666;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.07733333333333334,
                        translateY: constraints.maxHeight * 0.9777311743759527,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget345())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
