import 'package:flutter/material.dart';
import 'package:flutterapp/test1app/generatedpopupdeletecollectionwidget/generated/GeneratedPlusWidget3.dart';
import 'package:flutterapp/test1app/generatedpopupdeletecollectionwidget/generated/GeneratedRectangle367Widget83.dart';
import 'package:flutterapp/test1app/generatedpopupdeletecollectionwidget/generated/Generated2bookWidget1.dart';
import 'package:flutterapp/test1app/generatedpopupdeletecollectionwidget/generated/GeneratedComponent20Widget7.dart';
import 'package:flutterapp/test1app/generatedpopupdeletecollectionwidget/generated/GeneratedEllipse68Widget15.dart';
import 'package:flutterapp/test1app/generatedpopupdeletecollectionwidget/generated/GeneratedGroup33Widget70.dart';
import 'package:flutterapp/test1app/generatedpopupdeletecollectionwidget/generated/GeneratedGroup234Widget4.dart';
import 'package:flutterapp/test1app/generatedpopupdeletecollectionwidget/generated/GeneratedFromindividualreflectiontothepowerofpositivethoughtandf3.dart';
import 'package:flutterapp/test1app/generatedpopupdeletecollectionwidget/generated/GeneratedTitleWidget2.dart';
import 'package:flutterapp/test1app/generatedpopupdeletecollectionwidget/generated/GeneratedEllipse69Widget8.dart';
import 'package:flutterapp/test1app/generatedpopupdeletecollectionwidget/generated/GeneratedComponent19Widget7.dart';
import 'package:flutterapp/test1app/generatedpopupdeletecollectionwidget/generated/GeneratedSelectedWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/test1app/generatedpopupdeletecollectionwidget/generated/GeneratedRectangle392Widget4.dart';
import 'package:flutterapp/test1app/generatedpopupdeletecollectionwidget/generated/GeneratedEllipse67Widget5.dart';
import 'package:flutterapp/test1app/generatedpopupdeletecollectionwidget/generated/GeneratedDescriptionWidget2.dart';
import 'package:flutterapp/test1app/generatedpopupdeletecollectionwidget/generated/GeneratedYourbookhasstillbeenpurchasedWidget.dart';
import 'package:flutterapp/test1app/generatedpopupdeletecollectionwidget/generated/GeneratedGroup338Widget1.dart';
import 'package:flutterapp/test1app/generatedpopupdeletecollectionwidget/generated/GeneratedGroup341Widget1.dart';
import 'package:flutterapp/test1app/generatedpopupdeletecollectionwidget/generated/GeneratedBackWidget15.dart';
import 'package:flutterapp/test1app/generatedpopupdeletecollectionwidget/generated/GeneratedGroup339Widget1.dart';
import 'package:flutterapp/test1app/generatedpopupdeletecollectionwidget/generated/GeneratedRectangle393Widget3.dart';
import 'package:flutterapp/test1app/generatedpopupdeletecollectionwidget/generated/GeneratedRectangle32Widget9.dart';
import 'package:flutterapp/test1app/generatedpopupdeletecollectionwidget/generated/GeneratedIcon3d__1641Widget.dart';
import 'package:flutterapp/test1app/generatedpopupdeletecollectionwidget/generated/GeneratedGroup357Widget3.dart';

/* Frame popup delete collection
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPopupdeletecollectionWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 820.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 236, 240, 245),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -4.547473508864641e-13,
                right: null,
                bottom: null,
                width: 375.0,
                height: 820.0,
                child: GeneratedRectangle32Widget9(),
              ),
              Positioned(
                left: 29.05908203125,
                top: 312.33837890625,
                right: null,
                bottom: null,
                width: 213.58175659179688,
                height: 45.01531219482422,
                child: GeneratedRectangle367Widget83(),
              ),
              Positioned(
                left: 302.7130126953125,
                top: 266.84521484375,
                right: null,
                bottom: null,
                width: 42.9968147277832,
                height: 45.09751892089844,
                child: GeneratedGroup339Widget1(),
              ),
              Positioned(
                left: 29.0,
                top: 130.281982421875,
                right: null,
                bottom: null,
                width: 226.0,
                height: 42.0,
                child: GeneratedGroup33Widget70(),
              ),
              Positioned(
                left: 305.999755859375,
                top: 46.48046875,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse69Widget8(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.054835703531901044;

                  final double height =
                      constraints.maxHeight * 0.01829291320428616;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8419149576822916,
                        y: constraints.maxHeight * 0.07192719622356136,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup234Widget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 28.53173828125,
                top: 46.48046875,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse68Widget15(),
              ),
              Positioned(
                left: 44.0,
                top: 58.980224609375,
                right: null,
                bottom: null,
                width: 8.892169952392578,
                height: 15.0,
                child: GeneratedBackWidget15(),
              ),
              Positioned(
                left: 256.0,
                top: 46.033447265625,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse67Widget5(),
              ),
              Positioned(
                left: 268.5,
                top: 58.533447265625,
                right: null,
                bottom: null,
                width: 15.00003719329834,
                height: 15.00003719329834,
                child: GeneratedPlusWidget3(),
              ),
              Positioned(
                left: 29.0,
                top: 209.3251953125,
                right: null,
                bottom: null,
                width: 319.0001220703125,
                height: 38.0,
                child:
                    GeneratedFromindividualreflectiontothepowerofpositivethoughtandf3(),
              ),
              Positioned(
                left: 45.022216796875,
                top: 289.83056640625,
                right: null,
                bottom: null,
                width: 37.0,
                height: 20.0,
                child: Generated2bookWidget1(),
              ),
              Positioned(
                left: 29.0,
                top: 108.0,
                right: null,
                bottom: null,
                width: 322.0001220703125,
                height: 24.0,
                child: GeneratedTitleWidget2(),
              ),
              Positioned(
                left: 29.0,
                top: 184.3330078125,
                right: null,
                bottom: null,
                width: 322.0001220703125,
                height: 24.0,
                child: GeneratedDescriptionWidget2(),
              ),
              Positioned(
                left: 45.022216796875,
                top: 272.83056640625,
                right: null,
                bottom: null,
                width: 62.0,
                height: 22.0,
                child: GeneratedSelectedWidget1(),
              ),
              Positioned(
                left: 29.0,
                top: 341.70703125,
                right: null,
                bottom: null,
                width: 362.0542297363281,
                height: 500.134765625,
                child: GeneratedGroup338Widget1(),
              ),
              Positioned(
                left: 251.1783447265625,
                top: 266.84521484375,
                right: null,
                bottom: null,
                width: 42.9968147277832,
                height: 45.09751892089844,
                child: GeneratedGroup341Widget1(),
              ),
              Positioned(
                left: 0.0009765625,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 820.0,
                child: GeneratedRectangle392Widget4(),
              ),
              Positioned(
                left: 49.3994140625,
                top: 169.04833984375,
                right: null,
                bottom: null,
                width: 276.1983337402344,
                height: 305.1661682128906,
                child: GeneratedRectangle393Widget3(),
              ),
              Positioned(
                left: 84.31884765625,
                top: 190.58447265625,
                right: null,
                bottom: null,
                width: 206.3641357421875,
                height: 206.3641357421875,
                child: GeneratedGroup357Widget3(),
              ),
              Positioned(
                left: 121.5,
                top: 407.0498046875,
                right: null,
                bottom: null,
                width: 134.0,
                height: 59.0,
                child: GeneratedYourbookhasstillbeenpurchasedWidget(),
              ),
              Positioned(
                left: 33.978759765625,
                top: 137.901123046875,
                right: null,
                bottom: null,
                width: 311.7308349609375,
                height: 311.7308349609375,
                child: GeneratedIcon3d__1641Widget(),
              ),
              Positioned(
                left: 29.0,
                top: 720.0,
                right: null,
                bottom: null,
                width: 317.0,
                height: 64.41000366210938,
                child: GeneratedComponent19Widget7(),
              ),
              Positioned(
                left: 29.0,
                top: 646.82666015625,
                right: null,
                bottom: null,
                width: 317.0,
                height: 64.41000366210938,
                child: GeneratedComponent20Widget7(),
              )
            ]),
      ),
    ));
  }
}
