import 'package:flutter/material.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget3/generated/GeneratedMonaChalabiWidget4.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget3/generated/GeneratedEllipse74Widget21.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget3/generated/GeneratedBackWidget91.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget3/generated/GeneratedMonaChalabiWidget5.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget3/generated/GeneratedMaryJohnsonWidget4.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget3/generated/GeneratedEllipse75Widget9.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget3/generated/GeneratedEllipse76Widget7.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget3/generated/GeneratedEllipse78Widget5.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget3/generated/GeneratedEllipse79Widget5.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget3/generated/GeneratedMarkSmithWidget5.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget3/generated/GeneratedMarkSmithWidget4.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget3/generated/GeneratedLindaLeeWidget5.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget3/generated/GeneratedPatriciaWilliamsWidget4.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget3/generated/GeneratedLindaLeeWidget4.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget3/generated/GeneratedRectangle358Widget51.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget3/generated/GeneratedEllipse72Widget17.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget3/generated/GeneratedEllipse71Widget17.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget3/generated/GeneratedEllipse70Widget15.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget3/generated/GeneratedEllipse77Widget7.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget3/generated/GeneratedEllipse68Widget95.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget3/generated/GeneratedGroup337Widget3.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget3/generated/GeneratedPatriciaWilliamsWidget5.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget3/generated/GeneratedMaryJohnsonWidget5.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget3/generated/GeneratedEllipse73Widget23.dart';

/* Frame friend list_2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFriendlist_2Widget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 820.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 818.0,
                child: GeneratedRectangle358Widget51(),
              ),
              Positioned(
                left: 28.828125,
                top: 46.086181640625,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse68Widget95(),
              ),
              Positioned(
                left: 44.0,
                top: 58.980224609375,
                right: null,
                bottom: null,
                width: 8.892169952392578,
                height: 15.0,
                child: GeneratedBackWidget91(),
              ),
              Positioned(
                left: 80.06268310546875,
                top: 46.086181640625,
                right: null,
                bottom: null,
                width: 265.93731689453125,
                height: 40.0,
                child: GeneratedGroup337Widget3(),
              ),
              Positioned(
                left: 101.00048828125,
                top: 123.90986633300781,
                right: null,
                bottom: null,
                width: 99.0,
                height: 22.0,
                child: GeneratedMonaChalabiWidget4(),
              ),
              Positioned(
                left: 101.00048828125,
                top: 486.7158508300781,
                right: null,
                bottom: null,
                width: 99.0,
                height: 22.0,
                child: GeneratedMonaChalabiWidget5(),
              ),
              Positioned(
                left: 101.37646484375,
                top: 195.84046936035156,
                right: null,
                bottom: null,
                width: 77.0,
                height: 22.0,
                child: GeneratedMarkSmithWidget4(),
              ),
              Positioned(
                left: 101.37646484375,
                top: 558.6464233398438,
                right: null,
                bottom: null,
                width: 77.0,
                height: 22.0,
                child: GeneratedMarkSmithWidget5(),
              ),
              Positioned(
                left: 99.00048828125,
                top: 267.7710876464844,
                right: null,
                bottom: null,
                width: 112.0,
                height: 22.0,
                child: GeneratedPatriciaWilliamsWidget4(),
              ),
              Positioned(
                left: 99.00048828125,
                top: 630.5770263671875,
                right: null,
                bottom: null,
                width: 112.0,
                height: 22.0,
                child: GeneratedPatriciaWilliamsWidget5(),
              ),
              Positioned(
                left: 99.00048828125,
                top: 339.7016906738281,
                right: null,
                bottom: null,
                width: 97.0,
                height: 22.0,
                child: GeneratedMaryJohnsonWidget4(),
              ),
              Positioned(
                left: 99.00048828125,
                top: 702.5076293945312,
                right: null,
                bottom: null,
                width: 97.0,
                height: 22.0,
                child: GeneratedMaryJohnsonWidget5(),
              ),
              Positioned(
                left: 99.00048828125,
                top: 411.6322937011719,
                right: null,
                bottom: null,
                width: 67.0,
                height: 22.0,
                child: GeneratedLindaLeeWidget4(),
              ),
              Positioned(
                left: 99.00048828125,
                top: 774.438232421875,
                right: null,
                bottom: null,
                width: 67.0,
                height: 22.0,
                child: GeneratedLindaLeeWidget5(),
              ),
              Positioned(
                left: 28.94873046875,
                top: 108.66194152832031,
                right: null,
                bottom: null,
                width: 50.495826721191406,
                height: 50.495826721191406,
                child: GeneratedEllipse70Widget15(),
              ),
              Positioned(
                left: 28.94873046875,
                top: 471.4679260253906,
                right: null,
                bottom: null,
                width: 50.495826721191406,
                height: 50.495826721191406,
                child: GeneratedEllipse75Widget9(),
              ),
              Positioned(
                left: 28.94873046875,
                top: 181.2232208251953,
                right: null,
                bottom: null,
                width: 50.495826721191406,
                height: 50.495826721191406,
                child: GeneratedEllipse71Widget17(),
              ),
              Positioned(
                left: 28.94873046875,
                top: 544.0291748046875,
                right: null,
                bottom: null,
                width: 50.495826721191406,
                height: 50.495826721191406,
                child: GeneratedEllipse76Widget7(),
              ),
              Positioned(
                left: 28.94873046875,
                top: 253.7845001220703,
                right: null,
                bottom: null,
                width: 50.495826721191406,
                height: 50.495826721191406,
                child: GeneratedEllipse72Widget17(),
              ),
              Positioned(
                left: 28.94873046875,
                top: 616.5904541015625,
                right: null,
                bottom: null,
                width: 50.495826721191406,
                height: 50.495826721191406,
                child: GeneratedEllipse77Widget7(),
              ),
              Positioned(
                left: 28.94873046875,
                top: 326.3457946777344,
                right: null,
                bottom: null,
                width: 50.495826721191406,
                height: 50.495826721191406,
                child: GeneratedEllipse73Widget23(),
              ),
              Positioned(
                left: 28.94873046875,
                top: 689.1517333984375,
                right: null,
                bottom: null,
                width: 50.495826721191406,
                height: 50.495826721191406,
                child: GeneratedEllipse78Widget5(),
              ),
              Positioned(
                left: 28.94873046875,
                top: 398.9070739746094,
                right: null,
                bottom: null,
                width: 50.495826721191406,
                height: 50.495826721191406,
                child: GeneratedEllipse74Widget21(),
              ),
              Positioned(
                left: 28.94873046875,
                top: 761.7130126953125,
                right: null,
                bottom: null,
                width: 50.495826721191406,
                height: 50.495826721191406,
                child: GeneratedEllipse79Widget5(),
              )
            ]),
      ),
    ));
  }
}
