import 'package:flutter/material.dart';
import 'package:flutterapp/test1app/generatedcategorieswidget12/generated/GeneratedBackWidget52.dart';
import 'package:flutterapp/test1app/generatedcategorieswidget12/generated/GeneratedComponent15Widget7.dart';
import 'package:flutterapp/test1app/generatedcategorieswidget12/generated/GeneratedGroup337Widget2.dart';
import 'package:flutterapp/test1app/generatedcategorieswidget12/generated/GeneratedEllipse68Widget56.dart';
import 'package:flutterapp/test1app/generatedcategorieswidget12/generated/GeneratedComponent16Widget7.dart';
import 'package:flutterapp/test1app/generatedcategorieswidget12/generated/GeneratedHorrorfictionisfictioninanymediumintendedtoscareunsettl1.dart';
import 'package:flutterapp/test1app/generatedcategorieswidget12/generated/GeneratedBookshowWidget5.dart';
import 'package:flutterapp/test1app/generatedcategorieswidget12/generated/GeneratedComponent14Widget5.dart';
import 'package:flutterapp/test1app/generatedcategorieswidget12/generated/GeneratedRectangle328Widget13.dart';
import 'package:flutterapp/test1app/generatedcategorieswidget12/generated/GeneratedHorrorWidget103.dart';

/* Frame Categories
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCategoriesWidget12 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 820.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 252, 106, 67),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.000244140625,
                right: null,
                bottom: null,
                width: 375.0,
                height: 822.06005859375,
                child: GeneratedRectangle328Widget13(),
              ),
              Positioned(
                left: 28.6240234375,
                top: 390.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 110.0,
                child: GeneratedBookshowWidget5(),
              ),
              Positioned(
                left: 28.6240234375,
                top: 519.845703125,
                right: null,
                bottom: null,
                width: 315.0,
                height: 110.0,
                child: GeneratedComponent14Widget5(),
              ),
              Positioned(
                left: 28.6240234375,
                top: 649.6917114257812,
                right: null,
                bottom: null,
                width: 315.0,
                height: 110.0,
                child: GeneratedComponent15Widget7(),
              ),
              Positioned(
                left: 28.6240234375,
                top: 779.5377197265625,
                right: null,
                bottom: null,
                width: 315.0,
                height: 110.0,
                child: GeneratedComponent16Widget7(),
              ),
              Positioned(
                left: 0.0,
                top: -1.2783203125,
                right: null,
                bottom: null,
                width: 375.0,
                height: 397.092041015625,
                child: GeneratedGroup337Widget2(),
              ),
              Positioned(
                left: 29.0,
                top: 153.053466796875,
                right: null,
                bottom: null,
                width: 319.0,
                height: 192.19744873046875,
                child:
                    GeneratedHorrorfictionisfictioninanymediumintendedtoscareunsettl1(),
              ),
              Positioned(
                left: 29.0,
                top: 102.762939453125,
                right: null,
                bottom: null,
                width: 112.0,
                height: 47.0,
                child: GeneratedHorrorWidget103(),
              ),
              Positioned(
                left: 29.1884765625,
                top: 46.48046875,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse68Widget56(),
              ),
              Positioned(
                left: 43.0,
                top: 58.98046875,
                right: null,
                bottom: null,
                width: 8.892169952392578,
                height: 15.0,
                child: GeneratedBackWidget52(),
              )
            ]),
      ),
    ));
  }
}
