import 'package:flutter/material.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget/generated/GeneratedGroup280Widget4.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget/generated/GeneratedNataliaLebedinskaiaitwillfrequentlyoccurthatpleasures3W1.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget/generated/GeneratedGroup277Widget2.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget/generated/GeneratedEllipse73Widget10.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget/generated/GeneratedGroup279Widget4.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget/generated/GeneratedRectangle358Widget24.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget/generated/GeneratedGroup278Widget4.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget/generated/GeneratedEllipse70Widget6.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget/generated/GeneratedOleksandrLytvynenkoInafreehourandtheendWidget1.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget/generated/GeneratedRectangle373Widget8.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget/generated/GeneratedKissmarkWidget2.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget/generated/GeneratedBackWidget48.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget/generated/GeneratedEllipse72Widget7.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget/generated/GeneratedEllipse77Widget2.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget/generated/GeneratedRectangle374Widget14.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget/generated/GeneratedRectangle375Widget7.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget/generated/GeneratedRectangle372Widget9.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget/generated/GeneratedOuluPuluOntheotherhandwedenouncewithrighteousindignatio1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget/generated/GeneratedEllipse71Widget7.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget/generated/GeneratedEllipse68Widget51.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget/generated/GeneratedEllipse67Widget12.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget/generated/GeneratedEllipse66Widget19.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget/generated/GeneratedComponent7Widget5.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget/generated/GeneratedRectangle376Widget1.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget/generated/GeneratedVadimLiManythanksWidget1.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget/generated/GeneratedEllipse74Widget9.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget/generated/GeneratedGiseleYasharThisbookmyfavoritebookoftheyearMaybeeventhi1.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget/generated/GeneratedGroup336Widget4.dart';
import 'package:flutterapp/test1app/generatedfriendlist_2widget/generated/GeneratedEllipse76Widget2.dart';

/* Frame friend list_2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFriendlist_2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 820.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 236, 240, 245),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 818.0,
                child: GeneratedRectangle358Widget24(),
              ),
              Positioned(
                left: 305.828125,
                top: 46.086212158203125,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse66Widget19(),
              ),
              Positioned(
                left: 317.4736328125,
                top: 58.586212158203125,
                right: null,
                bottom: null,
                width: 16.709007263183594,
                height: 15.0,
                child: GeneratedGroup277Widget2(),
              ),
              Positioned(
                left: 28.828125,
                top: 46.086181640625,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse68Widget51(),
              ),
              Positioned(
                left: 44.0,
                top: 58.980224609375,
                right: null,
                bottom: null,
                width: 8.892169952392578,
                height: 15.0,
                child: GeneratedBackWidget48(),
              ),
              Positioned(
                left: 256.0,
                top: 46.086212158203125,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse67Widget12(),
              ),
              Positioned(
                left: 268.5,
                top: 58.586212158203125,
                right: null,
                bottom: null,
                width: 15.0,
                height: 15.0,
                child: GeneratedComponent7Widget5(),
              ),
              Positioned(
                left: 28.94873046875,
                top: 191.25857543945312,
                right: null,
                bottom: null,
                width: 88.77557373046875,
                height: 88.77557373046875,
                child: GeneratedGroup278Widget4(),
              ),
              Positioned(
                left: 257.052734375,
                top: 191.25857543945312,
                right: null,
                bottom: null,
                width: 88.77557373046875,
                height: 88.77557373046875,
                child: GeneratedGroup280Widget4(),
              ),
              Positioned(
                left: 128.1142578125,
                top: 166.26007080078125,
                right: null,
                bottom: null,
                width: 118.77255249023438,
                height: 118.77255249023438,
                child: GeneratedGroup279Widget4(),
              ),
              Positioned(
                left: 28.94873046875,
                top: 333.9653625488281,
                right: null,
                bottom: null,
                width: 50.495826721191406,
                height: 50.495826721191406,
                child: GeneratedEllipse70Widget6(),
              ),
              Positioned(
                left: 28.94873046875,
                top: 429.067138671875,
                right: null,
                bottom: null,
                width: 50.495826721191406,
                height: 50.495826721191406,
                child: GeneratedEllipse71Widget7(),
              ),
              Positioned(
                left: 28.94873046875,
                top: 501.18701171875,
                right: null,
                bottom: null,
                width: 50.495826721191406,
                height: 50.495826721191406,
                child: GeneratedEllipse72Widget7(),
              ),
              Positioned(
                left: 28.94873046875,
                top: 593.20947265625,
                right: null,
                bottom: null,
                width: 50.495826721191406,
                height: 50.495826721191406,
                child: GeneratedEllipse73Widget10(),
              ),
              Positioned(
                left: 28.94873046875,
                top: 665.3292846679688,
                right: null,
                bottom: null,
                width: 50.495826721191406,
                height: 50.495826721191406,
                child: GeneratedEllipse74Widget9(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.04;

                  final double height =
                      constraints.maxHeight * 0.01955990675019055;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.2508841145833333,
                        y: constraints.maxHeight * 0.1534803064858041,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedKissmarkWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 99.1240234375,
                top: 333.9653625488281,
                right: null,
                bottom: null,
                width: 251.0,
                height: 77.47772216796875,
                child: GeneratedRectangle372Widget9(),
              ),
              Positioned(
                left: 99.1240234375,
                top: 429.067138671875,
                right: null,
                bottom: null,
                width: 251.0,
                height: 54.495826721191406,
                child: GeneratedRectangle373Widget8(),
              ),
              Positioned(
                left: 99.1240234375,
                top: 593.20947265625,
                right: null,
                bottom: null,
                width: 247.0,
                height: 50.495826721191406,
                child: GeneratedRectangle375Widget7(),
              ),
              Positioned(
                left: 99.1240234375,
                top: 665.3292846679688,
                right: null,
                bottom: null,
                width: 247.0,
                height: 50.495826721191406,
                child: GeneratedRectangle376Widget1(),
              ),
              Positioned(
                left: 99.1240234375,
                top: 501.18701171875,
                right: null,
                bottom: null,
                width: 247.0,
                height: 70.39849853515625,
                child: GeneratedRectangle374Widget14(),
              ),
              Positioned(
                left: 113.5458984375,
                top: 342.0522766113281,
                right: null,
                bottom: null,
                width: 223.3353729248047,
                height: 58.0,
                child:
                    GeneratedGiseleYasharThisbookmyfavoritebookoftheyearMaybeeventhi1(),
              ),
              Positioned(
                left: 113.5458984375,
                top: 437.154052734375,
                right: null,
                bottom: null,
                width: 133.0,
                height: 20.0,
                child: GeneratedVadimLiManythanksWidget1(),
              ),
              Positioned(
                left: 113.5458984375,
                top: 601.29638671875,
                right: null,
                bottom: null,
                width: 218.0,
                height: 39.0,
                child:
                    GeneratedOleksandrLytvynenkoInafreehourandtheendWidget1(),
              ),
              Positioned(
                left: 113.5458984375,
                top: 673.4161987304688,
                right: null,
                bottom: null,
                width: 219.0,
                height: 39.0,
                child:
                    GeneratedNataliaLebedinskaiaitwillfrequentlyoccurthatpleasures3W1(),
              ),
              Positioned(
                left: 113.5458984375,
                top: 510.4349365234375,
                right: null,
                bottom: null,
                width: 192.0,
                height: 57.0,
                child:
                    GeneratedOuluPuluOntheotherhandwedenouncewithrighteousindignatio1(),
              ),
              Positioned(
                left: 29.0,
                top: 106.17306518554688,
                right: null,
                bottom: null,
                width: 317.00006103515625,
                height: 40.0,
                child: GeneratedGroup336Widget4(),
              ),
              Positioned(
                left: 70.21546936035156,
                top: 289.192626953125,
                right: null,
                bottom: null,
                width: 6.2417449951171875,
                height: 6.2417449951171875,
                child: GeneratedEllipse76Widget2(),
              ),
              Positioned(
                left: 184.37911987304688,
                top: 289.192626953125,
                right: null,
                bottom: null,
                width: 6.2417449951171875,
                height: 6.2417449951171875,
                child: GeneratedEllipse77Widget2(),
              )
            ]),
      ),
    ));
  }
}
