import 'package:flutter/material.dart';
import 'package:flutterapp/test1app/generatedpurchasedetailwidget1/generated/GeneratedRectangle302Widget2.dart';
import 'package:flutterapp/test1app/generatedpurchasedetailwidget1/generated/GeneratedComponent19Widget11.dart';
import 'package:flutterapp/test1app/generatedpurchasedetailwidget1/generated/GeneratedGroup33Widget87.dart';
import 'package:flutterapp/test1app/generatedpurchasedetailwidget1/generated/GeneratedDiscountcodeWidget.dart';
import 'package:flutterapp/test1app/generatedpurchasedetailwidget1/generated/GeneratedBackWidget20.dart';
import 'package:flutterapp/test1app/generatedpurchasedetailwidget1/generated/Generated035Widget.dart';
import 'package:flutterapp/test1app/generatedpurchasedetailwidget1/generated/GeneratedBookWidget16.dart';
import 'package:flutterapp/test1app/generatedpurchasedetailwidget1/generated/Generated000Widget.dart';
import 'package:flutterapp/test1app/generatedpurchasedetailwidget1/generated/GeneratedRectangle393Widget8.dart';
import 'package:flutterapp/test1app/generatedpurchasedetailwidget1/generated/Generated\$1000Widget1.dart';
import 'package:flutterapp/test1app/generatedpurchasedetailwidget1/generated/Generated\$1000Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/test1app/generatedpurchasedetailwidget1/generated/GeneratedGroup344Widget.dart';
import 'package:flutterapp/test1app/generatedpurchasedetailwidget1/generated/GeneratedTotalWidget.dart';
import 'package:flutterapp/test1app/generatedpurchasedetailwidget1/generated/GeneratedRectangle392Widget7.dart';
import 'package:flutterapp/test1app/generatedpurchasedetailwidget1/generated/GeneratedBookcoverWidget93.dart';
import 'package:flutterapp/test1app/generatedpurchasedetailwidget1/generated/GeneratedTaxFeesWidget.dart';
import 'package:flutterapp/test1app/generatedpurchasedetailwidget1/generated/GeneratedFrame135Widget1.dart';
import 'package:flutterapp/test1app/generatedpurchasedetailwidget1/generated/GeneratedFrame134Widget24.dart';
import 'package:flutterapp/test1app/generatedpurchasedetailwidget1/generated/GeneratedEllipse68Widget20.dart';
import 'package:flutterapp/test1app/generatedpurchasedetailwidget1/generated/GeneratedRectangle358Widget5.dart';

/* Frame Purchase detail
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPurchasedetailWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 820.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Image.asset(
                  "assets/images/67f8e51657c66919334759d2ab50821e86c501bf.png",
                  color: null,
                  fit: BoxFit.cover,
                  width: 375.0,
                  height: 820.0,
                  colorBlendMode: BlendMode.dstATop,
                ),
              ),
              Positioned(
                left: 0.0009765625,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 820.0,
                child: GeneratedRectangle392Widget7(),
              ),
              Positioned(
                left: 29.0009765625,
                top: 370.45068359375,
                right: null,
                bottom: null,
                width: 316.998779296875,
                height: 209.46368408203125,
                child: GeneratedRectangle358Widget5(),
              ),
              Positioned(
                left: 29.0009765625,
                top: 591.13232421875,
                right: null,
                bottom: null,
                width: 316.998779296875,
                height: 64.41000366210938,
                child: GeneratedRectangle393Widget8(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.134083984375;

                  final double height =
                      constraints.maxHeight * 0.03763611956340511;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.13066666666666665,
                        y: constraints.maxHeight * 0.7413493830983232,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup344Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 49.0,
                top: null,
                right: null,
                bottom: null,
                width: 275.5570983886719,
                height: 0.6036523580551147,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: 103.61,
                    z: 0,
                    child: GeneratedRectangle302Widget2()),
              ),
              Positioned(
                left: 49.0,
                top: 395.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 24.0,
                child: GeneratedBookWidget16(),
              ),
              Positioned(
                left: 274.0,
                top: 395.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 24.0,
                child: Generated$1000Widget(),
              ),
              Positioned(
                left: 274.0,
                top: 534.0751953125,
                right: null,
                bottom: null,
                width: 57.0,
                height: 24.0,
                child: Generated$1000Widget1(),
              ),
              Positioned(
                left: 289.0,
                top: 434.1630859375,
                right: null,
                bottom: null,
                width: 42.0,
                height: 24.0,
                child: Generated000Widget(),
              ),
              Positioned(
                left: 49.0,
                top: 434.4541015625,
                right: null,
                bottom: null,
                width: 79.0,
                height: 21.0,
                child: GeneratedTaxFeesWidget(),
              ),
              Positioned(
                left: 111.1728515625,
                top: 612.33740234375,
                right: null,
                bottom: null,
                width: 49.0,
                height: 24.0,
                child: Generated035Widget(),
              ),
              Positioned(
                left: 49.0,
                top: 473.908203125,
                right: null,
                bottom: null,
                width: 108.0,
                height: 21.0,
                child: GeneratedDiscountcodeWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.3333333333333333;

                  final double height =
                      constraints.maxHeight * 0.020731707317073172;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.536,
                        y: constraints.maxHeight * 0.5791563452743902,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFrame134Widget24(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.17066666666666666;

                  final double height =
                      constraints.maxHeight * 0.020731707317073172;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.6948189290364584,
                        y: constraints.maxHeight * 0.7498017101753048,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFrame135Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 49.0,
                top: 534.0751953125,
                right: null,
                bottom: null,
                width: 41.0,
                height: 24.0,
                child: GeneratedTotalWidget(),
              ),
              Positioned(
                left: 129.6943359375,
                top: 298.97802734375,
                right: null,
                bottom: null,
                width: 101.0,
                height: 42.299072265625,
                child: GeneratedGroup33Widget87(),
              ),
              Positioned(
                left: 103.42830657958984,
                top: 55.392578125,
                right: null,
                bottom: null,
                width: 168.1433868408203,
                height: 240.3837127685547,
                child: GeneratedBookcoverWidget93(),
              ),
              Positioned(
                left: 29.1884765625,
                top: 46.48046875,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse68Widget20(),
              ),
              Positioned(
                left: 43.0,
                top: 58.98046875,
                right: null,
                bottom: null,
                width: 8.892169952392578,
                height: 15.0,
                child: GeneratedBackWidget20(),
              ),
              Positioned(
                left: 30.0,
                top: 720.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 64.41000366210938,
                child: GeneratedComponent19Widget11(),
              )
            ]),
      ),
    ));
  }
}
