import 'package:flutter/material.dart';
import 'package:flutterapp/test1app/generatedfullviewwidget/generated/GeneratedCapa__11Widget1.dart';
import 'package:flutterapp/test1app/generatedfullviewwidget/generated/GeneratedGroup26Widget.dart';
import 'package:flutterapp/test1app/generatedfullviewwidget/generated/GeneratedIcon3d__1281Widget.dart';
import 'package:flutterapp/test1app/generatedfullviewwidget/generated/GeneratedRectangle442Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/test1app/generatedfullviewwidget/generated/GeneratedGroup25Widget1.dart';
import 'package:flutterapp/test1app/generatedfullviewwidget/generated/GeneratedEasyCustomizationWidget2.dart';
import 'package:flutterapp/test1app/generatedfullviewwidget/generated/GeneratedDarkModeWidget3.dart';
import 'package:flutterapp/test1app/generatedfullviewwidget/generated/GeneratedGroup374Widget.dart';
import 'package:flutterapp/test1app/generatedfullviewwidget/generated/GeneratedGroup22Widget1.dart';
import 'package:flutterapp/test1app/generatedfullviewwidget/generated/GeneratedA00141Widget1.dart';
import 'package:flutterapp/test1app/generatedfullviewwidget/generated/GeneratedLightModeWidget.dart';
import 'package:flutterapp/test1app/generatedfullviewwidget/generated/GeneratedRectangle365Widget1.dart';
import 'package:flutterapp/test1app/generatedfullviewwidget/generated/GeneratedImage1Widget.dart';
import 'package:flutterapp/test1app/generatedfullviewwidget/generated/Generated100ScreensWidget4.dart';
import 'package:flutterapp/test1app/generatedfullviewwidget/generated/Generated100ScreensWidget6.dart';
import 'package:flutterapp/test1app/generatedfullviewwidget/generated/GeneratedGroup373Widget.dart';
import 'package:flutterapp/test1app/generatedfullviewwidget/generated/Generated100ScreensWidget5.dart';
import 'package:flutterapp/test1app/generatedfullviewwidget/generated/GeneratedGroup23Widget1.dart';
import 'package:flutterapp/test1app/generatedfullviewwidget/generated/GeneratedGroup371Widget.dart';
import 'package:flutterapp/test1app/generatedfullviewwidget/generated/GeneratedGroup24Widget1.dart';
import 'package:flutterapp/test1app/generatedfullviewwidget/generated/GeneratedThanksForPurchasingWidget.dart';
import 'package:flutterapp/test1app/generatedfullviewwidget/generated/GeneratedGroup367Widget.dart';
import 'package:flutterapp/test1app/generatedfullviewwidget/generated/GeneratedGroup370Widget.dart';
import 'package:flutterapp/test1app/generatedfullviewwidget/generated/GeneratedDarkModeWidget4.dart';
import 'package:flutterapp/test1app/generatedfullviewwidget/generated/GeneratedDarkModeWidget2.dart';

/* Frame Full view
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFullviewWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 9840.705444335938,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 2112.098876953125,
                      height: 9422.30859375,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 252, 106, 67),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width = constraints.maxWidth;

                                final double height =
                                    constraints.maxHeight * 0.9577210584421695;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          -2.1530590061317314e-16,
                                      y: constraints.maxHeight *
                                          0.046729698073596115,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle365Widget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 2403.5703125,
                              top: 7885.71728515625,
                              right: null,
                              bottom: null,
                              width: 1351.8616943359375,
                              height: 1351.8616943359375,
                              child: GeneratedCapa__11Widget1(),
                            ),
                            Positioned(
                              left: -74.51930236816406,
                              top: 7923.78564453125,
                              right: null,
                              bottom: null,
                              width: 966.4154663085938,
                              height: 966.4154663085938,
                              child: GeneratedA00141Widget1(),
                            ),
                            Positioned(
                              left: -4.547473508864641e-13,
                              top: 7826.5,
                              right: null,
                              bottom: null,
                              width: 2112.098876953125,
                              height: 1595.80810546875,
                              child: GeneratedImage1Widget(),
                            ),
                            Positioned(
                              left: 224.48426818847656,
                              top: 8052.9990234375,
                              right: null,
                              bottom: null,
                              width: 1354.916748046875,
                              height: 161.580810546875,
                              child: GeneratedThanksForPurchasingWidget(),
                            ),
                            Positioned(
                              left: 1478.2086181640625,
                              top: 7856.357421875,
                              right: null,
                              bottom: null,
                              width: 552.8656005859375,
                              height: 552.8656005859375,
                              child: GeneratedIcon3d__1281Widget(),
                            ),
                            Positioned(
                              left: 1486.62158203125,
                              top: 8695.98046875,
                              right: null,
                              bottom: null,
                              width: 544.42822265625,
                              height: 1132.2698974609375,
                              child: GeneratedGroup25Widget1(),
                            ),
                            Positioned(
                              left: 81.02481842041016,
                              top: 8708.435546875,
                              right: null,
                              bottom: null,
                              width: 544.42822265625,
                              height: 1132.2698974609375,
                              child: GeneratedGroup26Widget(),
                            ),
                            Positioned(
                              left: 1188.055908203125,
                              top: 8556.4267578125,
                              right: null,
                              bottom: null,
                              width: 544.42822265625,
                              height: 1132.2698974609375,
                              child: GeneratedGroup23Widget1(),
                            ),
                            Positioned(
                              left: 379.5911865234375,
                              top: 8556.4267578125,
                              right: null,
                              bottom: null,
                              width: 544.42822265625,
                              height: 1132.2698974609375,
                              child: GeneratedGroup24Widget1(),
                            ),
                            Positioned(
                              left: 783.8233032226562,
                              top: 8370.9521484375,
                              right: null,
                              bottom: null,
                              width: 544.42822265625,
                              height: 1132.2698974609375,
                              child: GeneratedGroup22Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 2112.098876953125,
                              height: 1862.231201171875,
                              child: GeneratedGroup367Widget(),
                            ),
                            Positioned(
                              left: 1053.6231689453125,
                              top: 1892.50830078125,
                              right: null,
                              bottom: null,
                              width: 1138.75244140625,
                              height: 3113.606689453125,
                              child: GeneratedGroup371Widget(),
                            ),
                            Positioned(
                              left: 1278.14892578125,
                              top: 2037.992431640625,
                              right: null,
                              bottom: null,
                              width: 395.0850830078125,
                              height: 97.0444564819336,
                              child: GeneratedDarkModeWidget2(),
                            ),
                            Positioned(
                              left: 1278.14892578125,
                              top: 2037.992431640625,
                              right: null,
                              bottom: null,
                              width: 395.0850830078125,
                              height: 97.0444564819336,
                              child: GeneratedDarkModeWidget3(),
                            ),
                            Positioned(
                              left: 1278.14892578125,
                              top: 2037.992431640625,
                              right: null,
                              bottom: null,
                              width: 395.0850830078125,
                              height: 97.0444564819336,
                              child: GeneratedDarkModeWidget4(),
                            ),
                            Positioned(
                              left: 425.1122131347656,
                              top: 2037.992431640625,
                              right: null,
                              bottom: null,
                              width: 406.8189697265625,
                              height: 97.0444564819336,
                              child: GeneratedLightModeWidget(),
                            ),
                            Positioned(
                              left: -85.10269927978516,
                              top: 1471.2601318359375,
                              right: null,
                              bottom: null,
                              width: 1138.75244140625,
                              height: 3113.606689453125,
                              child: GeneratedGroup370Widget(),
                            ),
                            Positioned(
                              left: 1053.093017578125,
                              top: 2252.722412109375,
                              right: null,
                              bottom: null,
                              width: 1.8937819004058838,
                              height: 2551.26123046875,
                              child: GeneratedRectangle442Widget(),
                            ),
                            Positioned(
                              left: -169.0379638671875,
                              top: 4978.92431640625,
                              right: null,
                              bottom: null,
                              width: 2450.3486328125,
                              height: 1060.2713623046875,
                              child: GeneratedGroup373Widget(),
                            ),
                            Positioned(
                              left: 464.66180419921875,
                              top: 6177.708984375,
                              right: null,
                              bottom: null,
                              width: 1184.775390625,
                              height: 161.580810546875,
                              child: GeneratedEasyCustomizationWidget2(),
                            ),
                            Positioned(
                              left: 564.870361328125,
                              top: 4803.9833984375,
                              right: null,
                              bottom: null,
                              width: 982.3578491210938,
                              height: 120.38915252685547,
                              child: Generated100ScreensWidget4(),
                            ),
                            Positioned(
                              left: 564.870361328125,
                              top: 4803.9833984375,
                              right: null,
                              bottom: null,
                              width: 982.3577880859375,
                              height: 120.38915252685547,
                              child: Generated100ScreensWidget5(),
                            ),
                            Positioned(
                              left: 564.870361328125,
                              top: 4803.9833984375,
                              right: null,
                              bottom: null,
                              width: 982.3577880859375,
                              height: 120.38915252685547,
                              child: Generated100ScreensWidget6(),
                            ),
                            Positioned(
                              left: 128.3034210205078,
                              top: 6441.15478515625,
                              right: null,
                              bottom: null,
                              width: 1855.4920654296875,
                              height: 1291.1763916015625,
                              child: GeneratedGroup374Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
