import 'package:flutter/material.dart';
import 'package:flutterapp/test1app/generatedloginwidget/generated/GeneratedUnionWidget223.dart';
import 'package:flutterapp/test1app/generatedloginwidget/generated/GeneratedRectangle336Widget.dart';
import 'package:flutterapp/test1app/generatedloginwidget/generated/GeneratedFrame144Widget.dart';
import 'package:flutterapp/test1app/generatedloginwidget/generated/GeneratedTextBoxWidget15.dart';
import 'package:flutterapp/test1app/generatedloginwidget/generated/GeneratedTextBoxWidget14.dart';
import 'package:flutterapp/test1app/generatedloginwidget/generated/GeneratedButtonWidget8.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 820.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 252, 106, 67),
                ),
              ),
              Positioned(
                left: null,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 674.0,
                child: GeneratedFrame144Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 527.6943359375,
                right: null,
                bottom: null,
                width: 375.0,
                height: 292.3056640625,
                child: GeneratedRectangle336Widget(),
              ),
              Positioned(
                left: 330.27734375,
                top: 482.71826171875,
                right: null,
                bottom: null,
                width: 45.0,
                height: 47.0,
                child: GeneratedUnionWidget223(),
              ),
              Positioned(
                left: 30.0,
                top: 567.73486328125,
                right: null,
                bottom: null,
                width: 315.0,
                height: 55.0,
                child: GeneratedTextBoxWidget14(),
              ),
              Positioned(
                left: 30.0,
                top: 644.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 55.0,
                child: GeneratedTextBoxWidget15(),
              ),
              Positioned(
                left: 30.0,
                top: 720.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 64.41000366210938,
                child: GeneratedButtonWidget8(),
              )
            ]),
      ),
    ));
  }
}
