import 'package:flutter/material.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget/generated/GeneratedComponent7Widget4.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget/generated/GeneratedGroup284Widget.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget/generated/GeneratedRectangle374Widget9.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget/generated/GeneratedVadimLiManythanksWidget.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget/generated/GeneratedHorrororcomicWidget3.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget/generated/GeneratedRectangle372Widget5.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget/generated/GeneratedGroup279Widget3.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget/generated/GeneratedEllipse71Widget6.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget/generated/GeneratedEllipse73Widget8.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget/generated/GeneratedRectangle373Widget6.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget/generated/GeneratedGroup336Widget3.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget/generated/GeneratedGroup282Widget.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget/generated/GeneratedRectangle375Widget5.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget/generated/GeneratedEllipse67Widget11.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget/generated/GeneratedGiseleYasharThisbookmyfavoritebookoftheyearMaybeeventhi.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget/generated/GeneratedEllipse74Widget7.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget/generated/GeneratedEllipse72Widget6.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget/generated/GeneratedEllipse66Widget18.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget/generated/GeneratedNataliaLebedinskaiaitwillfrequentlyoccurthatpleasures3W.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget/generated/GeneratedRectangle358Widget22.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget/generated/GeneratedGroup278Widget3.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget/generated/GeneratedOleksandrLytvynenkoInafreehourandtheendWidget.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget/generated/GeneratedBackWidget46.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget/generated/GeneratedKissmarkWidget1.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget/generated/GeneratedRectangle376Widget.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget/generated/GeneratedCallme035586961Widget.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget/generated/GeneratedGroup283Widget.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget/generated/GeneratedThatbookfkingbadWidget.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget/generated/GeneratedEllipse68Widget49.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget/generated/GeneratedGroup277Widget1.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget/generated/GeneratedOuluPuluOntheotherhandwedenouncewithrighteousindignatio.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget/generated/GeneratedEllipse70Widget5.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget/generated/GeneratedGroup280Widget3.dart';

/* Frame friend list_first seen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFriendlist_firstseenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 820.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 236, 240, 245),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 818.0,
                child: GeneratedRectangle358Widget22(),
              ),
              Positioned(
                left: 305.828125,
                top: 46.086212158203125,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse66Widget18(),
              ),
              Positioned(
                left: 28.94873046875,
                top: 191.25857543945312,
                right: null,
                bottom: null,
                width: 88.77557373046875,
                height: 88.77557373046875,
                child: GeneratedGroup278Widget3(),
              ),
              Positioned(
                left: 257.052734375,
                top: 191.25857543945312,
                right: null,
                bottom: null,
                width: 88.77557373046875,
                height: 88.77557373046875,
                child: GeneratedGroup280Widget3(),
              ),
              Positioned(
                left: 128.1142578125,
                top: 166.26007080078125,
                right: null,
                bottom: null,
                width: 118.77255249023438,
                height: 118.77255249023438,
                child: GeneratedGroup279Widget3(),
              ),
              Positioned(
                left: 28.94873046875,
                top: 333.9653625488281,
                right: null,
                bottom: null,
                width: 50.495826721191406,
                height: 50.495826721191406,
                child: GeneratedEllipse70Widget5(),
              ),
              Positioned(
                left: 28.94873046875,
                top: 429.067138671875,
                right: null,
                bottom: null,
                width: 50.495826721191406,
                height: 50.495826721191406,
                child: GeneratedEllipse71Widget6(),
              ),
              Positioned(
                left: 28.94873046875,
                top: 501.18701171875,
                right: null,
                bottom: null,
                width: 50.495826721191406,
                height: 50.495826721191406,
                child: GeneratedEllipse72Widget6(),
              ),
              Positioned(
                left: 28.94873046875,
                top: 593.20947265625,
                right: null,
                bottom: null,
                width: 50.495826721191406,
                height: 50.495826721191406,
                child: GeneratedEllipse73Widget8(),
              ),
              Positioned(
                left: 28.94873046875,
                top: 665.3292846679688,
                right: null,
                bottom: null,
                width: 50.495826721191406,
                height: 50.495826721191406,
                child: GeneratedEllipse74Widget7(),
              ),
              Positioned(
                left: 28.828125,
                top: 46.086181640625,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse68Widget49(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.04;

                  final double height =
                      constraints.maxHeight * 0.01955990675019055;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.2508841145833333,
                        y: constraints.maxHeight * 0.1534803064858041,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedKissmarkWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 99.1240234375,
                top: 333.9653625488281,
                right: null,
                bottom: null,
                width: 251.0,
                height: 77.47772216796875,
                child: GeneratedRectangle372Widget5(),
              ),
              Positioned(
                left: 99.1240234375,
                top: 429.067138671875,
                right: null,
                bottom: null,
                width: 251.0,
                height: 54.495826721191406,
                child: GeneratedRectangle373Widget6(),
              ),
              Positioned(
                left: 99.1240234375,
                top: 593.20947265625,
                right: null,
                bottom: null,
                width: 247.0,
                height: 50.495826721191406,
                child: GeneratedRectangle375Widget5(),
              ),
              Positioned(
                left: 99.1240234375,
                top: 665.3292846679688,
                right: null,
                bottom: null,
                width: 247.0,
                height: 50.495826721191406,
                child: GeneratedRectangle376Widget(),
              ),
              Positioned(
                left: 99.1240234375,
                top: 501.18701171875,
                right: null,
                bottom: null,
                width: 247.0,
                height: 70.39849853515625,
                child: GeneratedRectangle374Widget9(),
              ),
              Positioned(
                left: 256.0,
                top: 46.086212158203125,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse67Widget11(),
              ),
              Positioned(
                left: 268.5,
                top: 58.586212158203125,
                right: null,
                bottom: null,
                width: 15.0,
                height: 15.0,
                child: GeneratedComponent7Widget4(),
              ),
              Positioned(
                left: 113.5458984375,
                top: 342.0522766113281,
                right: null,
                bottom: null,
                width: 223.3353729248047,
                height: 58.0,
                child:
                    GeneratedGiseleYasharThisbookmyfavoritebookoftheyearMaybeeventhi(),
              ),
              Positioned(
                left: 113.5458984375,
                top: 437.154052734375,
                right: null,
                bottom: null,
                width: 133.0,
                height: 20.0,
                child: GeneratedVadimLiManythanksWidget(),
              ),
              Positioned(
                left: 113.5458984375,
                top: 601.29638671875,
                right: null,
                bottom: null,
                width: 218.0,
                height: 39.0,
                child: GeneratedOleksandrLytvynenkoInafreehourandtheendWidget(),
              ),
              Positioned(
                left: 113.5458984375,
                top: 673.4161987304688,
                right: null,
                bottom: null,
                width: 219.0,
                height: 39.0,
                child:
                    GeneratedNataliaLebedinskaiaitwillfrequentlyoccurthatpleasures3W(),
              ),
              Positioned(
                left: 113.5458984375,
                top: 510.4349365234375,
                right: null,
                bottom: null,
                width: 192.0,
                height: 57.0,
                child:
                    GeneratedOuluPuluOntheotherhandwedenouncewithrighteousindignatio(),
              ),
              Positioned(
                left: 43.0,
                top: 58.980224609375,
                right: null,
                bottom: null,
                width: 8.892169952392578,
                height: 15.0,
                child: GeneratedBackWidget46(),
              ),
              Positioned(
                left: 317.4736328125,
                top: 58.586212158203125,
                right: null,
                bottom: null,
                width: 16.709007263183594,
                height: 15.0,
                child: GeneratedGroup277Widget1(),
              ),
              Positioned(
                left: 29.0,
                top: 106.17306518554688,
                right: null,
                bottom: null,
                width: 317.00006103515625,
                height: 40.0,
                child: GeneratedGroup336Widget3(),
              ),
              Positioned(
                left: 244.94384765625,
                top: 192.0198516845703,
                right: null,
                bottom: null,
                width: 118.07815551757812,
                height: 41.61197280883789,
                child: GeneratedGroup282Widget(),
              ),
              Positioned(
                left: 345.828125,
                top: 213.34999084472656,
                right: null,
                bottom: null,
                width: 89.6842041015625,
                height: 48.21748733520508,
                child: GeneratedGroup283Widget(),
              ),
              Positioned(
                left: 115.66552734375,
                top: 213.34999084472656,
                right: null,
                bottom: null,
                width: 89.6842041015625,
                height: 48.21748733520508,
                child: GeneratedGroup284Widget(),
              ),
              Positioned(
                left: 139.2265625,
                top: 157.1324920654297,
                right: null,
                bottom: null,
                width: 91.0,
                height: 20.0,
                child: GeneratedHorrororcomicWidget3(),
              ),
              Positioned(
                left: 268.486328125,
                top: 167.80519104003906,
                right: null,
                bottom: null,
                width: 67.0,
                height: 38.0,
                child: GeneratedThatbookfkingbadWidget(),
              ),
              Positioned(
                left: 33.56591796875,
                top: 168.72056579589844,
                right: null,
                bottom: null,
                width: 60.0,
                height: 38.0,
                child: GeneratedCallme035586961Widget(),
              )
            ]),
      ),
    ));
  }
}
