import 'package:flutter/material.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget9/generated/GeneratedReviewWidget13.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget9/generated/GeneratedRatingWidget13.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget9/generated/GeneratedReadsWidget13.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget9/generated/GeneratedGroup106Widget12.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget9/generated/Generated156Widget22.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget9/generated/GeneratedGroup164Widget14.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget9/generated/GeneratedShareWidget22.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget9/generated/GeneratedEllipse66Widget24.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget9/generated/GeneratedBackWidget76.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget9/generated/GeneratedEllipse68Widget79.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget9/generated/Generated50Widget21.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget9/generated/GeneratedRectangle32Widget40.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget9/generated/GeneratedBookcoverWidget207.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget9/generated/GeneratedGroup257Widget7.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget9/generated/GeneratedGroup33Widget190.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget9/generated/GeneratedRectangle328Widget17.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget9/generated/Generated412Widget13.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget9/generated/GeneratedAtveroeosetaccusamusetiustoodiodignissimosducimusquibla12.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget9/generated/GeneratedRectangle2Widget17.dart';
import 'package:flutterapp/test1app/generatedbookreviewwidget9/generated/GeneratedItemstatusBarsdarkWidget13.dart';

/* Frame Book review
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBookreviewWidget9 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 820.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: -69.4482421875,
                top: -142.09051513671875,
                right: null,
                bottom: null,
                width: 513.8966674804688,
                height: 661.0578002929688,
                child: GeneratedRectangle32Widget40(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.9999982096354166;

                  final double height =
                      constraints.maxHeight * 0.23990675763386052;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.0000013020833333333333,
                        y: constraints.maxHeight * 0.4273309847203697,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle2Widget17(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 173.0,
                top: 368.176513671875,
                right: null,
                bottom: null,
                width: 39.0,
                height: 23.0,
                child: GeneratedRatingWidget13(),
              ),
              Positioned(
                left: 83.0625,
                top: 368.176513671875,
                right: null,
                bottom: null,
                width: 37.0,
                height: 23.0,
                child: GeneratedReadsWidget13(),
              ),
              Positioned(
                left: 256.015625,
                top: 368.176513671875,
                right: null,
                bottom: null,
                width: 43.0,
                height: 23.0,
                child: GeneratedReviewWidget13(),
              ),
              Positioned(
                left: 176.0,
                top: 387.176513671875,
                right: null,
                bottom: null,
                width: 30.0,
                height: 24.0,
                child: Generated50Widget21(),
              ),
              Positioned(
                left: 83.98388671875,
                top: 387.176513671875,
                right: null,
                bottom: null,
                width: 31.0,
                height: 24.0,
                child: Generated412Widget13(),
              ),
              Positioned(
                left: 258.515625,
                top: 387.176513671875,
                right: null,
                bottom: null,
                width: 31.0,
                height: 24.0,
                child: Generated156Widget22(),
              ),
              Positioned(
                left: 0.0,
                top: 421.5306091308594,
                right: null,
                bottom: null,
                width: 375.0,
                height: 392.4694519042969,
                child: GeneratedRectangle328Widget17(),
              ),
              Positioned(
                left: 103.42833709716797,
                top: 55.392578125,
                right: null,
                bottom: null,
                width: 168.1433868408203,
                height: 240.3837127685547,
                child: GeneratedBookcoverWidget207(),
              ),
              Positioned(
                left: 0.0,
                top: 745.0,
                right: null,
                bottom: null,
                width: 374.99981689453125,
                height: 75.0,
                child: GeneratedGroup257Widget7(),
              ),
              Positioned(
                left: 29.00048828125,
                top: 507.96728515625,
                right: null,
                bottom: null,
                width: 77.0,
                height: 19.0,
                child: GeneratedGroup106Widget12(),
              ),
              Positioned(
                left: 29.00048828125,
                top: 538.802490234375,
                right: null,
                bottom: null,
                width: 327.0,
                height: 192.19744873046875,
                child:
                    GeneratedAtveroeosetaccusamusetiustoodiodignissimosducimusquibla12(),
              ),
              Positioned(
                left: 29.00048828125,
                top: 450.5909729003906,
                right: null,
                bottom: null,
                width: 99.0,
                height: 42.23786926269531,
                child: GeneratedGroup164Widget14(),
              ),
              Positioned(
                left: 125.06278991699219,
                top: 298.97802734375,
                right: null,
                bottom: null,
                width: 125.0,
                height: 42.299072265625,
                child: GeneratedGroup33Widget190(),
              ),
              Positioned(
                left: 0.0,
                top: -1776.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -5.922666666666666,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedItemstatusBarsdarkWidget13(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 29.46875,
                top: 46.480255126953125,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse68Widget79(),
              ),
              Positioned(
                left: 44.0,
                top: 58.980224609375,
                right: null,
                bottom: null,
                width: 8.892169952392578,
                height: 15.0,
                child: GeneratedBackWidget76(),
              ),
              Positioned(
                left: 305.828125,
                top: 46.08642578125,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse66Widget24(),
              ),
              Positioned(
                left: 317.0,
                top: 58.58642578125,
                right: null,
                bottom: null,
                width: 15.0,
                height: 15.0,
                child: GeneratedShareWidget22(),
              )
            ]),
      ),
    ));
  }
}
