import 'package:flutter/material.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget1/generated/GeneratedThatbookfkingbadWidget1.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget1/generated/GeneratedVadimLiManythanksWidget2.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget1/generated/GeneratedKissmarkWidget4.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget1/generated/GeneratedNataliaLebedinskaiaitwillfrequentlyoccurthatpleasures3W2.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget1/generated/GeneratedRectangle358Widget48.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget1/generated/GeneratedOleksandrLytvynenkoInafreehourandtheendWidget2.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget1/generated/GeneratedEllipse72Widget15.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget1/generated/GeneratedBackWidget88.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget1/generated/GeneratedCallme035586961Widget1.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget1/generated/GeneratedRectangle373Widget15.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget1/generated/GeneratedGroup280Widget8.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget1/generated/GeneratedRectangle372Widget15.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget1/generated/GeneratedEllipse68Widget92.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget1/generated/GeneratedRectangle374Widget24.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget1/generated/GeneratedGroup279Widget8.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget1/generated/GeneratedEllipse71Widget15.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget1/generated/GeneratedEllipse73Widget20.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget1/generated/GeneratedRectangle376Widget2.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget1/generated/GeneratedGroup277Widget4.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget1/generated/GeneratedEllipse74Widget18.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget1/generated/GeneratedGroup283Widget1.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget1/generated/GeneratedGroup278Widget8.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget1/generated/GeneratedOuluPuluOntheotherhandwedenouncewithrighteousindignatio2.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget1/generated/GeneratedEllipse70Widget13.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget1/generated/GeneratedGroup282Widget1.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget1/generated/GeneratedComponent7Widget10.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget1/generated/GeneratedEllipse67Widget23.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget1/generated/GeneratedEllipse66Widget36.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget1/generated/GeneratedHorrororcomicWidget8.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget1/generated/GeneratedRectangle375Widget13.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget1/generated/GeneratedGroup336Widget8.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget1/generated/GeneratedGiseleYasharThisbookmyfavoritebookoftheyearMaybeeventhi2.dart';
import 'package:flutterapp/test1app/generatedfriendlist_firstseenwidget1/generated/GeneratedGroup284Widget1.dart';

/* Frame friend list_first seen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFriendlist_firstseenWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 820.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 818.0,
                child: GeneratedRectangle358Widget48(),
              ),
              Positioned(
                left: 305.828125,
                top: 46.086212158203125,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse66Widget36(),
              ),
              Positioned(
                left: 28.94873046875,
                top: 191.25857543945312,
                right: null,
                bottom: null,
                width: 88.77557373046875,
                height: 88.77557373046875,
                child: GeneratedGroup278Widget8(),
              ),
              Positioned(
                left: 257.052734375,
                top: 191.25857543945312,
                right: null,
                bottom: null,
                width: 88.77557373046875,
                height: 88.77557373046875,
                child: GeneratedGroup280Widget8(),
              ),
              Positioned(
                left: 128.1142578125,
                top: 166.26007080078125,
                right: null,
                bottom: null,
                width: 118.77255249023438,
                height: 118.77255249023438,
                child: GeneratedGroup279Widget8(),
              ),
              Positioned(
                left: 28.94873046875,
                top: 333.9653625488281,
                right: null,
                bottom: null,
                width: 50.495826721191406,
                height: 50.495826721191406,
                child: GeneratedEllipse70Widget13(),
              ),
              Positioned(
                left: 28.94873046875,
                top: 429.067138671875,
                right: null,
                bottom: null,
                width: 50.495826721191406,
                height: 50.495826721191406,
                child: GeneratedEllipse71Widget15(),
              ),
              Positioned(
                left: 28.94873046875,
                top: 501.18701171875,
                right: null,
                bottom: null,
                width: 50.495826721191406,
                height: 50.495826721191406,
                child: GeneratedEllipse72Widget15(),
              ),
              Positioned(
                left: 28.94873046875,
                top: 593.20947265625,
                right: null,
                bottom: null,
                width: 50.495826721191406,
                height: 50.495826721191406,
                child: GeneratedEllipse73Widget20(),
              ),
              Positioned(
                left: 28.94873046875,
                top: 665.3292846679688,
                right: null,
                bottom: null,
                width: 50.495826721191406,
                height: 50.495826721191406,
                child: GeneratedEllipse74Widget18(),
              ),
              Positioned(
                left: 28.828125,
                top: 46.086181640625,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse68Widget92(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.04;

                  final double height =
                      constraints.maxHeight * 0.01955990675019055;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.2508841145833333,
                        y: constraints.maxHeight * 0.1534803064858041,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedKissmarkWidget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 99.1240234375,
                top: 333.9653625488281,
                right: null,
                bottom: null,
                width: 251.0,
                height: 77.47772216796875,
                child: GeneratedRectangle372Widget15(),
              ),
              Positioned(
                left: 99.1240234375,
                top: 429.067138671875,
                right: null,
                bottom: null,
                width: 251.0,
                height: 54.495826721191406,
                child: GeneratedRectangle373Widget15(),
              ),
              Positioned(
                left: 99.1240234375,
                top: 593.20947265625,
                right: null,
                bottom: null,
                width: 247.0,
                height: 50.495826721191406,
                child: GeneratedRectangle375Widget13(),
              ),
              Positioned(
                left: 99.1240234375,
                top: 665.3292846679688,
                right: null,
                bottom: null,
                width: 247.0,
                height: 50.495826721191406,
                child: GeneratedRectangle376Widget2(),
              ),
              Positioned(
                left: 99.1240234375,
                top: 501.18701171875,
                right: null,
                bottom: null,
                width: 247.0,
                height: 70.39849853515625,
                child: GeneratedRectangle374Widget24(),
              ),
              Positioned(
                left: 256.0,
                top: 46.086212158203125,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse67Widget23(),
              ),
              Positioned(
                left: 268.5,
                top: 58.586212158203125,
                right: null,
                bottom: null,
                width: 15.0,
                height: 15.0,
                child: GeneratedComponent7Widget10(),
              ),
              Positioned(
                left: 113.5458984375,
                top: 342.0522766113281,
                right: null,
                bottom: null,
                width: 223.3353729248047,
                height: 58.0,
                child:
                    GeneratedGiseleYasharThisbookmyfavoritebookoftheyearMaybeeventhi2(),
              ),
              Positioned(
                left: 113.5458984375,
                top: 437.154052734375,
                right: null,
                bottom: null,
                width: 133.0,
                height: 20.0,
                child: GeneratedVadimLiManythanksWidget2(),
              ),
              Positioned(
                left: 113.5458984375,
                top: 601.29638671875,
                right: null,
                bottom: null,
                width: 218.0,
                height: 39.0,
                child:
                    GeneratedOleksandrLytvynenkoInafreehourandtheendWidget2(),
              ),
              Positioned(
                left: 113.5458984375,
                top: 673.4161987304688,
                right: null,
                bottom: null,
                width: 219.0,
                height: 39.0,
                child:
                    GeneratedNataliaLebedinskaiaitwillfrequentlyoccurthatpleasures3W2(),
              ),
              Positioned(
                left: 113.5458984375,
                top: 510.4349365234375,
                right: null,
                bottom: null,
                width: 192.0,
                height: 57.0,
                child:
                    GeneratedOuluPuluOntheotherhandwedenouncewithrighteousindignatio2(),
              ),
              Positioned(
                left: 43.0,
                top: 58.980224609375,
                right: null,
                bottom: null,
                width: 8.892169952392578,
                height: 15.0,
                child: GeneratedBackWidget88(),
              ),
              Positioned(
                left: 317.4736328125,
                top: 58.586212158203125,
                right: null,
                bottom: null,
                width: 16.709007263183594,
                height: 15.0,
                child: GeneratedGroup277Widget4(),
              ),
              Positioned(
                left: 29.0,
                top: 106.17306518554688,
                right: null,
                bottom: null,
                width: 317.00006103515625,
                height: 40.0,
                child: GeneratedGroup336Widget8(),
              ),
              Positioned(
                left: 244.94384765625,
                top: 192.0198516845703,
                right: null,
                bottom: null,
                width: 118.07815551757812,
                height: 41.61197280883789,
                child: GeneratedGroup282Widget1(),
              ),
              Positioned(
                left: 345.828125,
                top: 213.34999084472656,
                right: null,
                bottom: null,
                width: 89.6842041015625,
                height: 48.21748733520508,
                child: GeneratedGroup283Widget1(),
              ),
              Positioned(
                left: 115.66552734375,
                top: 213.34999084472656,
                right: null,
                bottom: null,
                width: 89.6842041015625,
                height: 48.21748733520508,
                child: GeneratedGroup284Widget1(),
              ),
              Positioned(
                left: 139.2265625,
                top: 160.1324462890625,
                right: null,
                bottom: null,
                width: 91.0,
                height: 16.0,
                child: GeneratedHorrororcomicWidget8(),
              ),
              Positioned(
                left: 268.486328125,
                top: 170.80517578125,
                right: null,
                bottom: null,
                width: 67.0,
                height: 30.0,
                child: GeneratedThatbookfkingbadWidget1(),
              ),
              Positioned(
                left: 33.56591796875,
                top: 171.7205810546875,
                right: null,
                bottom: null,
                width: 60.0,
                height: 30.0,
                child: GeneratedCallme035586961Widget1(),
              )
            ]),
      ),
    ));
  }
}
