import 'package:flutter/material.dart';
import 'package:flutterapp/test1app/generatednotificationemptywidget/generated/GeneratedEllipse67Widget1.dart';
import 'package:flutterapp/test1app/generatednotificationemptywidget/generated/GeneratedUnionWidget120.dart';
import 'package:flutterapp/test1app/generatednotificationemptywidget/generated/GeneratedEllipse87StrokeWidget19.dart';
import 'package:flutterapp/test1app/generatednotificationemptywidget/generated/GeneratedBell1Widget1.dart';
import 'package:flutterapp/test1app/generatednotificationemptywidget/generated/GeneratedIconWidget51.dart';
import 'package:flutterapp/test1app/generatednotificationemptywidget/generated/GeneratedBackWidget7.dart';
import 'package:flutterapp/test1app/generatednotificationemptywidget/generated/GeneratedNoNotificationsRightNowWidget.dart';
import 'package:flutterapp/test1app/generatednotificationemptywidget/generated/GeneratedRectangle358Widget2.dart';
import 'package:flutterapp/test1app/generatednotificationemptywidget/generated/GeneratedEllipse87StrokeWidget18.dart';
import 'package:flutterapp/test1app/generatednotificationemptywidget/generated/GeneratedEllipse71Widget2.dart';
import 'package:flutterapp/test1app/generatednotificationemptywidget/generated/GeneratedEllipse89Widget4.dart';
import 'package:flutterapp/test1app/generatednotificationemptywidget/generated/GeneratedEllipse88Widget4.dart';
import 'package:flutterapp/test1app/generatednotificationemptywidget/generated/GeneratedUnionWidget121.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/test1app/generatednotificationemptywidget/generated/GeneratedEllipse87StrokeWidget17.dart';
import 'package:flutterapp/test1app/generatednotificationemptywidget/generated/GeneratedEllipse87StrokeWidget16.dart';
import 'package:flutterapp/test1app/generatednotificationemptywidget/generated/GeneratedComponent7Widget1.dart';
import 'package:flutterapp/test1app/generatednotificationemptywidget/generated/GeneratedEllipse86Widget4.dart';
import 'package:flutterapp/test1app/generatednotificationemptywidget/generated/GeneratedVector7StrokeWidget9.dart';
import 'package:flutterapp/test1app/generatednotificationemptywidget/generated/GeneratedEllipse68Widget8.dart';
import 'package:flutterapp/test1app/generatednotificationemptywidget/generated/GeneratedVector7StrokeWidget8.dart';
import 'package:flutterapp/test1app/generatednotificationemptywidget/generated/GeneratedNotificationsWidget1.dart';

/* Frame notification empty
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNotificationemptyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 820.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 818.0,
                child: GeneratedRectangle358Widget2(),
              ),
              Positioned(
                left: 28.828125,
                top: 46.086181640625,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse68Widget8(),
              ),
              Positioned(
                left: 28.828125,
                top: 102.3125,
                right: null,
                bottom: null,
                width: 212.0,
                height: 47.0,
                child: GeneratedNotificationsWidget1(),
              ),
              Positioned(
                left: 42.2528076171875,
                top: 234.56640625,
                right: null,
                bottom: null,
                width: 290.494384765625,
                height: 290.494384765625,
                child: GeneratedEllipse86Widget4(),
              ),
              Positioned(
                left: 70.2647476196289,
                top: 229.1084747314453,
                right: null,
                bottom: null,
                width: 276.8744201660156,
                height: 276.8744201660156,
                child: GeneratedBell1Widget1(),
              ),
              Positioned(
                left: 94.778076171875,
                top: 596.9267578125,
                right: null,
                bottom: null,
                width: 205.0,
                height: 21.0,
                child: GeneratedNoNotificationsRightNowWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.061584065755208334;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      23.094024658203125;

                  double percentHeight = 0.028232295338700458;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      23.150482177734375;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.7819588216145833,
                        translateY: constraints.maxHeight * 0.3458882773794779,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedEllipse87StrokeWidget16())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.04211121622721354;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      15.791706085205078;

                  double percentHeight = 0.019304284816834986;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      15.829513549804688;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.21404451497395832,
                        translateY: constraints.maxHeight * 0.36263636147103656,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedEllipse87StrokeWidget17())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.05075589497884114;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 19.03346061706543;

                  double percentHeight = 0.023267080725693123;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      19.07900619506836;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.17800960286458334,
                        translateY: constraints.maxHeight * 0.589717362566692,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedEllipse87StrokeWidget18())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.02593940734863281;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 9.727277755737305;

                  double percentHeight = 0.011833714275825314;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      9.703645706176758;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.7858975423177084,
                        translateY: constraints.maxHeight * 0.5826327812380907,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedEllipse87StrokeWidget19())
                  ]);
                }),
              ),
              Positioned(
                left: 310.8179626464844,
                top: 384.7734375,
                right: null,
                bottom: null,
                width: 13.97461223602295,
                height: 13.97461223602295,
                child: GeneratedUnionWidget120(),
              ),
              Positioned(
                left: 104.778076171875,
                top: 493.9213562011719,
                right: null,
                bottom: null,
                width: 13.97461223602295,
                height: 13.97461223602295,
                child: GeneratedUnionWidget121(),
              ),
              Positioned(
                left: 123.49951171875,
                top: 279.28515625,
                right: null,
                bottom: null,
                width: 7.3029351234436035,
                height: 7.3029351234436035,
                child: GeneratedEllipse88Widget4(),
              ),
              Positioned(
                left: 215.744140625,
                top: 512.08349609375,
                right: null,
                bottom: null,
                width: 10.880300521850586,
                height: 10.880300521850586,
                child: GeneratedEllipse89Widget4(),
              ),
              Positioned(
                left: 64.56146240234375,
                top: 361.00634765625,
                right: null,
                bottom: null,
                width: 16.59978675842285,
                height: 9.662408828735352,
                child: GeneratedVector7StrokeWidget8(),
              ),
              Positioned(
                left: 273.6935119628906,
                top: 374.0619201660156,
                right: null,
                bottom: null,
                width: 10.426594734191895,
                height: 6.069115161895752,
                child: GeneratedVector7StrokeWidget9(),
              ),
              Positioned(
                left: 305.999755859375,
                top: 46.48046875,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse71Widget2(),
              ),
              Positioned(
                left: 316.999755859375,
                top: 59.0,
                right: null,
                bottom: null,
                width: 18.0,
                height: 18.0,
                child: GeneratedComponent7Widget1(),
              ),
              Positioned(
                left: 256.0,
                top: 46.08642578125,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse67Widget1(),
              ),
              Positioned(
                left: 266.625,
                top: 58.98046875,
                right: null,
                bottom: null,
                width: 18.7500057220459,
                height: 15.0,
                child: GeneratedIconWidget51(),
              ),
              Positioned(
                left: 44.0,
                top: 58.980224609375,
                right: null,
                bottom: null,
                width: 8.892169952392578,
                height: 15.0,
                child: GeneratedBackWidget7(),
              )
            ]),
      ),
    ));
  }
}
