import 'package:flutter/material.dart';
import 'package:flutterapp/test1app/generatedcomponent7widget12/generated/GeneratedRectangle367StrokeWidget4.dart';
import 'package:flutterapp/test1app/generatedcomponent7widget12/generated/GeneratedRectangle367StrokeStrokeWidget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/test1app/generatedcomponent7widget12/generated/GeneratedGroup274Widget4.dart';

/* Component Component 7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedComponent7Widget12 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 13.608535766601562,
      height: 13.608535766601562,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.9630226080872435;
                double scaleX =
                    (constraints.maxWidth * percentWidth) / 13.105327606201172;

                double percentHeight = 0.9630226080872435;
                double scaleY = (constraints.maxHeight * percentHeight) /
                    13.105327606201172;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.01847334424745669,
                      translateY: constraints.maxHeight * 0.01850124231021731,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedRectangle367StrokeWidget4())
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 1.0000255088024992;
                double scaleX =
                    (constraints.maxWidth * percentWidth) / 13.608882904052734;

                double percentHeight = 1.0000255088024992;
                double scaleY = (constraints.maxHeight * percentHeight) /
                    13.608882904052734;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX:
                          constraints.maxWidth * -0.00002550880249907776,
                      translateY: constraints.maxHeight * -7.46046681878246e-8,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedRectangle367StrokeStrokeWidget4())
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.19206562013300457;

                final double height =
                    constraints.maxHeight * 0.7945214100144755;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.2854121220352324,
                      y: constraints.maxHeight * 0.5582733175683328,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedGroup274Widget4(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
