import 'package:flutter/material.dart';
import 'package:flutterapp/test1app/generatedgetstartwidget3/generated/GeneratedTextBoxWidget25.dart';
import 'package:flutterapp/test1app/generatedgetstartwidget3/generated/GeneratedIcon_backWidget26.dart';
import 'package:flutterapp/test1app/generatedgetstartwidget3/generated/GeneratedGroup33Widget145.dart';
import 'package:flutterapp/test1app/generatedgetstartwidget3/generated/GeneratedTextBoxWidget28.dart';
import 'package:flutterapp/test1app/generatedgetstartwidget3/generated/GeneratedVectorWidget553.dart';
import 'package:flutterapp/test1app/generatedgetstartwidget3/generated/GeneratedEllipse68Widget58.dart';
import 'package:flutterapp/test1app/generatedgetstartwidget3/generated/Generated84355869631Widget1.dart';
import 'package:flutterapp/test1app/generatedgetstartwidget3/generated/Generated18081996Widget1.dart';
import 'package:flutterapp/test1app/generatedgetstartwidget3/generated/GeneratedIc24cameraWidget2.dart';
import 'package:flutterapp/test1app/generatedgetstartwidget3/generated/GeneratedIc24calendarselectdayWidget2.dart';
import 'package:flutterapp/test1app/generatedgetstartwidget3/generated/GeneratedMapWidget2.dart';
import 'package:flutterapp/test1app/generatedgetstartwidget3/generated/GeneratedButtonWidget17.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/test1app/generatedgetstartwidget3/generated/GeneratedEllipse62Widget7.dart';
import 'package:flutterapp/test1app/generatedgetstartwidget3/generated/GeneratedEllipse61Widget4.dart';
import 'package:flutterapp/test1app/generatedgetstartwidget3/generated/GeneratedEllipse64Widget7.dart';
import 'package:flutterapp/test1app/generatedgetstartwidget3/generated/GeneratedBackWidget54.dart';
import 'package:flutterapp/test1app/generatedgetstartwidget3/generated/Generated7BtTchPhng4TnBnhWidget1.dart';
import 'package:flutterapp/test1app/generatedgetstartwidget3/generated/GeneratedTextBoxWidget26.dart';
import 'package:flutterapp/test1app/generatedgetstartwidget3/generated/GeneratedBaodesignerWidget1.dart';
import 'package:flutterapp/test1app/generatedgetstartwidget3/generated/GeneratedTextBoxWidget27.dart';

/* Frame Get start
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGetstartWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 820.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 18, 18, 18),
                ),
              ),
              Positioned(
                left: 30.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 55.0,
                child: GeneratedTextBoxWidget25(),
              ),
              Positioned(
                left: 29.73651123046875,
                top: 412.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 55.0,
                child: GeneratedTextBoxWidget26(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.058666666666666666;

                  final double height =
                      constraints.maxHeight * 0.027027037085556403;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.12845149739583334,
                        y: constraints.maxHeight * 0.5224620912133193,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedIc24calendarselectdayWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 331.98876953125,
                top: 447.0,
                right: null,
                bottom: null,
                width: 8.892169952392578,
                height: 15.0,
                child: GeneratedIcon_backWidget26(),
              ),
              Positioned(
                left: 30.0,
                top: 488.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 55.0,
                child: GeneratedTextBoxWidget27(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.064;

                  final double height =
                      constraints.maxHeight * 0.029484037073647103;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.12578483072916666,
                        y: constraints.maxHeight * 0.6151450552591463,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedMapWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 30.0,
                top: 564.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 55.0,
                child: GeneratedTextBoxWidget28(),
              ),
              Positioned(
                left: 30.0,
                top: 722.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 64.41000366210938,
                child: GeneratedButtonWidget17(),
              ),
              Positioned(
                left: 123.79278564453125,
                top: 173.86767578125,
                right: null,
                bottom: null,
                width: 127.41444396972656,
                height: 127.41444396972656,
                child: GeneratedEllipse61Widget4(),
              ),
              Positioned(
                left: 123.6826171875,
                top: 174.0,
                right: null,
                bottom: null,
                width: 127.28187561035156,
                height: 127.28187561035156,
                child: GeneratedEllipse64Widget7(),
              ),
              Positioned(
                left: 213.11328125,
                top: 274.580322265625,
                right: null,
                bottom: null,
                width: 26.701797485351562,
                height: 26.701797485351562,
                child: GeneratedEllipse62Widget7(),
              ),
              Positioned(
                left: 218.0,
                top: 279.368896484375,
                right: null,
                bottom: null,
                width: 17.0,
                height: 17.125320434570312,
                child: GeneratedIc24cameraWidget2(),
              ),
              Positioned(
                left: 50.2281494140625,
                top: 582.43359375,
                right: null,
                bottom: null,
                width: 18.00436019897461,
                height: 18.0,
                child: GeneratedVectorWidget553(),
              ),
              Positioned(
                left: 28.5322265625,
                top: 46.086181640625,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse68Widget58(),
              ),
              Positioned(
                left: 44.0,
                top: 58.980224609375,
                right: null,
                bottom: null,
                width: 8.892169952392578,
                height: 15.0,
                child: GeneratedBackWidget54(),
              ),
              Positioned(
                left: 29.0,
                top: 102.762939453125,
                right: null,
                bottom: null,
                width: 175.0,
                height: 42.0,
                child: GeneratedGroup33Widget145(),
              ),
              Positioned(
                left: 88.4404296875,
                top: 355.64111328125,
                right: null,
                bottom: null,
                width: 71.0,
                height: 23.0,
                child: GeneratedBaodesignerWidget1(),
              ),
              Positioned(
                left: 88.4404296875,
                top: 432.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 20.0,
                child: Generated18081996Widget1(),
              ),
              Positioned(
                left: 88.44085693359375,
                top: 506.0,
                right: null,
                bottom: null,
                width: 169.0,
                height: 20.0,
                child: Generated7BtTchPhng4TnBnhWidget1(),
              ),
              Positioned(
                left: 88.44085693359375,
                top: 582.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 23.0,
                child: Generated84355869631Widget1(),
              )
            ]),
      ),
    ));
  }
}
