import 'package:flutter/material.dart';
import 'package:flutterapp/test1app/generatedframe1widget/generated/GeneratedEllipse6Widget.dart';
import 'package:flutterapp/test1app/generatedframe1widget/generated/GeneratedFullyOrganizedLayersWidget.dart';
import 'package:flutterapp/test1app/generatedframe1widget/generated/GeneratedSettingsWidget.dart';
import 'package:flutterapp/test1app/generatedframe1widget/generated/GeneratedGroup364Widget.dart';
import 'package:flutterapp/test1app/generatedframe1widget/generated/GeneratedOnlinebookreadingapplicationWidget.dart';
import 'package:flutterapp/test1app/generatedframe1widget/generated/GeneratedGroup19Widget.dart';
import 'package:flutterapp/test1app/generatedframe1widget/generated/GeneratedGroup24Widget.dart';
import 'package:flutterapp/test1app/generatedframe1widget/generated/GeneratedGroup21Widget.dart';
import 'package:flutterapp/test1app/generatedframe1widget/generated/GeneratedRectangle365Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/test1app/generatedframe1widget/generated/GeneratedA00141Widget.dart';
import 'package:flutterapp/test1app/generatedframe1widget/generated/GeneratedEasyCustomizationWidget.dart';
import 'package:flutterapp/test1app/generatedframe1widget/generated/GeneratedRectangleWidget2.dart';
import 'package:flutterapp/test1app/generatedframe1widget/generated/Generated100ScreensWidget.dart';
import 'package:flutterapp/test1app/generatedframe1widget/generated/GeneratedKookReaderWidget.dart';
import 'package:flutterapp/test1app/generatedframe1widget/generated/GeneratedEllipse4Widget.dart';
import 'package:flutterapp/test1app/generatedframe1widget/generated/GeneratedAndDarkModeWidget.dart';
import 'package:flutterapp/test1app/generatedframe1widget/generated/GeneratedGroup22Widget.dart';
import 'package:flutterapp/test1app/generatedframe1widget/generated/GeneratedUnionWidget2.dart';
import 'package:flutterapp/test1app/generatedframe1widget/generated/GeneratedEllipse5Widget.dart';
import 'package:flutterapp/test1app/generatedframe1widget/generated/GeneratedEllipse3Widget.dart';
import 'package:flutterapp/test1app/generatedframe1widget/generated/GeneratedImageWidget.dart';
import 'package:flutterapp/test1app/generatedframe1widget/generated/GeneratedIc24viewlpWidget.dart';
import 'package:flutterapp/test1app/generatedframe1widget/generated/GeneratedFreeGoogleFontWidget.dart';
import 'package:flutterapp/test1app/generatedframe1widget/generated/GeneratedCapa__11Widget.dart';
import 'package:flutterapp/test1app/generatedframe1widget/generated/GeneratedIc24substractWidget.dart';
import 'package:flutterapp/test1app/generatedframe1widget/generated/GeneratedGroup20Widget.dart';
import 'package:flutterapp/test1app/generatedframe1widget/generated/GeneratedUiKitWidget.dart';
import 'package:flutterapp/test1app/generatedframe1widget/generated/GeneratedGroup25Widget.dart';
import 'package:flutterapp/test1app/generatedframe1widget/generated/GeneratedDarkModeWidget.dart';
import 'package:flutterapp/test1app/generatedframe1widget/generated/Generated100ScreensWidget1.dart';
import 'package:flutterapp/test1app/generatedframe1widget/generated/GeneratedKookReaderWidget1.dart';
import 'package:flutterapp/test1app/generatedframe1widget/generated/GeneratedAndDarkModeWidget1.dart';
import 'package:flutterapp/test1app/generatedframe1widget/generated/GeneratedRectangleWidget1.dart';
import 'package:flutterapp/test1app/generatedframe1widget/generated/GeneratedGroup23Widget.dart';

/* Frame Frame1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1810.1961059570312,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1800.0,
                      height: 1360.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 252, 106, 67),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width = constraints.maxWidth;

                                final double height =
                                    constraints.maxHeight * 1.0012469123391543;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: 0,
                                      y: 0,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle365Widget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 1888.727294921875,
                              top: -171.284423828125,
                              right: null,
                              bottom: null,
                              width: 1532.980224609375,
                              height: 1532.980224609375,
                              child: GeneratedCapa__11Widget(),
                            ),
                            Positioned(
                              left: 152.8224334716797,
                              top: 703.4367065429688,
                              right: null,
                              bottom: null,
                              width: 823.6109619140625,
                              height: 823.6109619140625,
                              child: GeneratedA00141Widget(),
                            ),
                            Positioned(
                              left: 74.11041259765625,
                              top: 802.6104125976562,
                              right: null,
                              bottom: null,
                              width: 43.779170989990234,
                              height: 43.779170989990234,
                              child: GeneratedEllipse3Widget(),
                            ),
                            Positioned(
                              left: 74.11041259765625,
                              top: 877.0130615234375,
                              right: null,
                              bottom: null,
                              width: 43.779170989990234,
                              height: 43.779170989990234,
                              child: GeneratedEllipse4Widget(),
                            ),
                            Positioned(
                              left: 74.11041259765625,
                              top: 947.147705078125,
                              right: null,
                              bottom: null,
                              width: 43.779170989990234,
                              height: 43.779170989990234,
                              child: GeneratedEllipse5Widget(),
                            ),
                            Positioned(
                              left: 74.11041259765625,
                              top: 1021.012939453125,
                              right: null,
                              bottom: null,
                              width: 43.779170989990234,
                              height: 43.779170989990234,
                              child: GeneratedEllipse6Widget(),
                            ),
                            Positioned(
                              left: 84.0,
                              top: 1030.9024658203125,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedIc24substractWidget(),
                            ),
                            Positioned(
                              left: 77.68524169921875,
                              top: 72.83074951171875,
                              right: null,
                              bottom: null,
                              width: 81.73149108886719,
                              height: 81.72840118408203,
                              child: GeneratedRectangleWidget1(),
                            ),
                            Positioned(
                              left: 178.5126495361328,
                              top: 72.83074951171875,
                              right: null,
                              bottom: null,
                              width: 81.73149108886719,
                              height: 81.72840118408203,
                              child: GeneratedRectangleWidget2(),
                            ),
                            Positioned(
                              left: 202.50338745117188,
                              top: 88.6949462890625,
                              right: null,
                              bottom: null,
                              width: 33.75,
                              height: 50.0,
                              child: GeneratedImageWidget(),
                            ),
                            Positioned(
                              left: 66.92132568359375,
                              top: 194.34912109375,
                              right: null,
                              bottom: null,
                              width: 569.0,
                              height: 323.0,
                              child: GeneratedKookReaderWidget(),
                            ),
                            Positioned(
                              left: 66.92132568359375,
                              top: 194.34912109375,
                              right: null,
                              bottom: null,
                              width: 569.0,
                              height: 323.0,
                              child: GeneratedKookReaderWidget1(),
                            ),
                            Positioned(
                              left: 77.10687255859375,
                              top: 1132.3292236328125,
                              right: null,
                              bottom: null,
                              width: 336.0,
                              height: 52.0,
                              child: Generated100ScreensWidget(),
                            ),
                            Positioned(
                              left: 77.10687255859375,
                              top: 1132.3292236328125,
                              right: null,
                              bottom: null,
                              width: 336.0,
                              height: 52.0,
                              child: Generated100ScreensWidget1(),
                            ),
                            Positioned(
                              left: 77.26495361328125,
                              top: 1197.431396484375,
                              right: null,
                              bottom: null,
                              width: 386.0,
                              height: 52.0,
                              child: GeneratedAndDarkModeWidget(),
                            ),
                            Positioned(
                              left: 77.26495361328125,
                              top: 1197.431396484375,
                              right: null,
                              bottom: null,
                              width: 386.0,
                              height: 52.0,
                              child: GeneratedAndDarkModeWidget1(),
                            ),
                            Positioned(
                              left: 77.10687255859375,
                              top: 676.87744140625,
                              right: null,
                              bottom: null,
                              width: 511.0,
                              height: 44.0,
                              child:
                                  GeneratedOnlinebookreadingapplicationWidget(),
                            ),
                            Positioned(
                              left: 134.8297119140625,
                              top: 803.4952392578125,
                              right: null,
                              bottom: null,
                              width: 366.0,
                              height: 44.0,
                              child: GeneratedFullyOrganizedLayersWidget(),
                            ),
                            Positioned(
                              left: 84.0,
                              top: 813.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 23.0,
                              child: GeneratedIc24viewlpWidget(),
                            ),
                            Positioned(
                              left: 134.8297119140625,
                              top: 876.2108764648438,
                              right: null,
                              bottom: null,
                              width: 277.0,
                              height: 44.0,
                              child: GeneratedFreeGoogleFontWidget(),
                            ),
                            Positioned(
                              left: 85.60072326660156,
                              top: 888.414794921875,
                              right: null,
                              bottom: null,
                              width: 20.798545837402344,
                              height: 20.79607582092285,
                              child: GeneratedGroup364Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.012222222222222223;

                                final double height = constraints.maxHeight *
                                    0.016176470588235296;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.04722222222222222,
                                      y: constraints.maxHeight *
                                          0.7044117647058824,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedSettingsWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 134.8297119140625,
                              top: 948.9268798828125,
                              right: null,
                              bottom: null,
                              width: 317.0,
                              height: 44.0,
                              child: GeneratedEasyCustomizationWidget(),
                            ),
                            Positioned(
                              left: 134.8297119140625,
                              top: 1022.7921142578125,
                              right: null,
                              bottom: null,
                              width: 177.0,
                              height: 44.0,
                              child: GeneratedDarkModeWidget(),
                            ),
                            Positioned(
                              left: 71.5880126953125,
                              top: 507.87744140625,
                              right: null,
                              bottom: null,
                              width: 346.0,
                              height: 171.0,
                              child: GeneratedUiKitWidget(),
                            ),
                            Positioned(
                              left: 102.51528930664062,
                              top: 88.6949462890625,
                              right: null,
                              bottom: null,
                              width: 32.0713996887207,
                              height: 50.0,
                              child: GeneratedUnionWidget2(),
                            ),
                            Positioned(
                              left: 805.0,
                              top: 300.619384765625,
                              right: null,
                              bottom: null,
                              width: 349.7822265625,
                              height: 727.2883911132812,
                              child: GeneratedGroup19Widget(),
                            ),
                            Positioned(
                              left: 1621.46240234375,
                              top: -200.71160888671875,
                              right: null,
                              bottom: null,
                              width: 349.7822265625,
                              height: 727.2883911132812,
                              child: GeneratedGroup24Widget(),
                            ),
                            Positioned(
                              left: 1213.231201171875,
                              top: 29.0,
                              right: null,
                              bottom: null,
                              width: 349.7822265625,
                              height: 727.2883911132812,
                              child: GeneratedGroup22Widget(),
                            ),
                            Positioned(
                              left: 805.0,
                              top: 1082.90771484375,
                              right: null,
                              bottom: null,
                              width: 349.7822265625,
                              height: 727.2883911132812,
                              child: GeneratedGroup21Widget(),
                            ),
                            Positioned(
                              left: 1621.46240234375,
                              top: 581.5767211914062,
                              right: null,
                              bottom: null,
                              width: 349.7822265625,
                              height: 727.2883911132812,
                              child: GeneratedGroup25Widget(),
                            ),
                            Positioned(
                              left: 1213.231201171875,
                              top: 811.288330078125,
                              right: null,
                              bottom: null,
                              width: 349.7822265625,
                              height: 727.2883911132812,
                              child: GeneratedGroup23Widget(),
                            ),
                            Positioned(
                              left: 805.0,
                              top: -481.66900634765625,
                              right: null,
                              bottom: null,
                              width: 349.7822265625,
                              height: 727.2883911132812,
                              child: GeneratedGroup20Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
