import 'package:flutter/material.dart';
import 'package:flutterapp/test1app/generatedrecoverypassword_3widget1/generated/GeneratedResetcodewassenttoyouremailPleaseenterthecodeandcreaten4.dart';
import 'package:flutterapp/test1app/generatedrecoverypassword_3widget1/generated/GeneratedEllipse95Widget1.dart';
import 'package:flutterapp/test1app/generatedrecoverypassword_3widget1/generated/GeneratedEllipse94Widget1.dart';
import 'package:flutterapp/test1app/generatedrecoverypassword_3widget1/generated/GeneratedEllipse100Widget1.dart';
import 'package:flutterapp/test1app/generatedrecoverypassword_3widget1/generated/GeneratedEllipse99Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/test1app/generatedrecoverypassword_3widget1/generated/GeneratedEllipse92Widget1.dart';
import 'package:flutterapp/test1app/generatedrecoverypassword_3widget1/generated/GeneratedEllipse96Widget1.dart';
import 'package:flutterapp/test1app/generatedrecoverypassword_3widget1/generated/GeneratedEllipse98Widget1.dart';
import 'package:flutterapp/test1app/generatedrecoverypassword_3widget1/generated/GeneratedEllipse93Widget1.dart';
import 'package:flutterapp/test1app/generatedrecoverypassword_3widget1/generated/GeneratedTextBoxWidget34.dart';
import 'package:flutterapp/test1app/generatedrecoverypassword_3widget1/generated/GeneratedTextBoxWidget32.dart';
import 'package:flutterapp/test1app/generatedrecoverypassword_3widget1/generated/GeneratedEllipse97Widget1.dart';
import 'package:flutterapp/test1app/generatedrecoverypassword_3widget1/generated/GeneratedEllipse91Widget1.dart';
import 'package:flutterapp/test1app/generatedrecoverypassword_3widget1/generated/GeneratedRecoveryPasswordWidget5.dart';
import 'package:flutterapp/test1app/generatedrecoverypassword_3widget1/generated/GeneratedEllipse101Widget1.dart';
import 'package:flutterapp/test1app/generatedrecoverypassword_3widget1/generated/GeneratedTextBoxWidget33.dart';
import 'package:flutterapp/test1app/generatedrecoverypassword_3widget1/generated/GeneratedButtonWidget19.dart';

/* Frame Recovery Password_3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRecoveryPassword_3Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 820.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 18, 18, 18),
                ),
              ),
              Positioned(
                left: 30.0,
                top: 124.0663070678711,
                right: null,
                bottom: null,
                width: 317.0,
                height: 44.0,
                child: GeneratedRecoveryPasswordWidget5(),
              ),
              Positioned(
                left: 30.0,
                top: 720.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 64.41000366210938,
                child: GeneratedButtonWidget19(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.7727913411458334;

                  final double height =
                      constraints.maxHeight * 0.04666506139243521;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.12819010416666668,
                        y: constraints.maxHeight * 0.22155421187237995,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child:
                              GeneratedResetcodewassenttoyouremailPleaseenterthecodeandcreaten4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 30.0,
                top: 252.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 55.0,
                child: GeneratedTextBoxWidget32(),
              ),
              Positioned(
                left: 30.0,
                top: 328.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 55.0,
                child: GeneratedTextBoxWidget33(),
              ),
              Positioned(
                left: 30.0,
                top: 404.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 55.0,
                child: GeneratedTextBoxWidget34(),
              ),
              Positioned(
                left: 79.38528442382812,
                top: 352.5557861328125,
                right: null,
                bottom: null,
                width: 5.888454437255859,
                height: 5.888454437255859,
                child: GeneratedEllipse91Widget1(),
              ),
              Positioned(
                left: 93.69950103759766,
                top: 352.5557861328125,
                right: null,
                bottom: null,
                width: 5.888454437255859,
                height: 5.888454437255859,
                child: GeneratedEllipse92Widget1(),
              ),
              Positioned(
                left: 108.01376342773438,
                top: 352.5557861328125,
                right: null,
                bottom: null,
                width: 5.888454437255859,
                height: 5.888454437255859,
                child: GeneratedEllipse93Widget1(),
              ),
              Positioned(
                left: 122.32803344726562,
                top: 352.5557861328125,
                right: null,
                bottom: null,
                width: 5.888454437255859,
                height: 5.888454437255859,
                child: GeneratedEllipse94Widget1(),
              ),
              Positioned(
                left: 136.64224243164062,
                top: 352.5557861328125,
                right: null,
                bottom: null,
                width: 5.888454437255859,
                height: 5.888454437255859,
                child: GeneratedEllipse95Widget1(),
              ),
              Positioned(
                left: 150.95645141601562,
                top: 352.5557861328125,
                right: null,
                bottom: null,
                width: 5.888454437255859,
                height: 5.888454437255859,
                child: GeneratedEllipse96Widget1(),
              ),
              Positioned(
                left: 165.27066040039062,
                top: 352.5557861328125,
                right: null,
                bottom: null,
                width: 5.888454437255859,
                height: 5.888454437255859,
                child: GeneratedEllipse97Widget1(),
              ),
              Positioned(
                left: 179.58486938476562,
                top: 352.5557861328125,
                right: null,
                bottom: null,
                width: 5.888454437255859,
                height: 5.888454437255859,
                child: GeneratedEllipse98Widget1(),
              ),
              Positioned(
                left: 193.89907836914062,
                top: 352.5557861328125,
                right: null,
                bottom: null,
                width: 5.888454437255859,
                height: 5.888454437255859,
                child: GeneratedEllipse99Widget1(),
              ),
              Positioned(
                left: 208.21328735351562,
                top: 352.5557861328125,
                right: null,
                bottom: null,
                width: 5.888454437255859,
                height: 5.888454437255859,
                child: GeneratedEllipse100Widget1(),
              ),
              Positioned(
                left: 222.52749633789062,
                top: 352.5557861328125,
                right: null,
                bottom: null,
                width: 5.888454437255859,
                height: 5.888454437255859,
                child: GeneratedEllipse101Widget1(),
              )
            ]),
      ),
    ));
  }
}
