import 'package:flutter/material.dart';
import 'package:flutterapp/test1app/generatedbook_quicknextpagewidget/generated/GeneratedRectangle303Widget.dart';
import 'package:flutterapp/test1app/generatedbook_quicknextpagewidget/generated/GeneratedBackWidget28.dart';
import 'package:flutterapp/test1app/generatedbook_quicknextpagewidget/generated/GeneratedEllipse68Widget28.dart';
import 'package:flutterapp/test1app/generatedbook_quicknextpagewidget/generated/GeneratedAAWidget.dart';
import 'package:flutterapp/test1app/generatedbook_quicknextpagewidget/generated/GeneratedRectangle300Widget.dart';
import 'package:flutterapp/test1app/generatedbook_quicknextpagewidget/generated/GeneratedRectangle302Widget5.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/test1app/generatedbook_quicknextpagewidget/generated/GeneratedGroup165Widget.dart';
import 'package:flutterapp/test1app/generatedbook_quicknextpagewidget/generated/Generated208337Widget.dart';
import 'package:flutterapp/test1app/generatedbook_quicknextpagewidget/generated/GeneratedStartWidget.dart';
import 'package:flutterapp/test1app/generatedbook_quicknextpagewidget/generated/GeneratedRectangle304Widget.dart';
import 'package:flutterapp/test1app/generatedbook_quicknextpagewidget/generated/GeneratedGroup8Widget1.dart';
import 'package:flutterapp/test1app/generatedbook_quicknextpagewidget/generated/GeneratedButImustexplaintoyouhowallthismistakenideaofdenouncingp.dart';
import 'package:flutterapp/test1app/generatedbook_quicknextpagewidget/generated/GeneratedGroup166Widget.dart';
import 'package:flutterapp/test1app/generatedbook_quicknextpagewidget/generated/GeneratedShareWidget3.dart';
import 'package:flutterapp/test1app/generatedbook_quicknextpagewidget/generated/GeneratedRectangle13Widget6.dart';

/* Frame Book_Quick  next page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBook_QuicknextpageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 820.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 820.0,
                child: GeneratedRectangle300Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 776.316162109375,
                right: null,
                bottom: null,
                width: 325.0,
                height: 3.198465585708618,
                child: GeneratedRectangle302Widget5(),
              ),
              Positioned(
                left: 25.0,
                top: 102.91785430908203,
                right: null,
                bottom: null,
                width: 327.0,
                height: 607.783203125,
                child:
                    GeneratedButImustexplaintoyouhowallthismistakenideaofdenouncingp(),
              ),
              Positioned(
                left: 25.0,
                top: 776.316162109375,
                right: null,
                bottom: null,
                width: 201.93020629882812,
                height: 3.198465585708618,
                child: GeneratedRectangle303Widget(),
              ),
              Positioned(
                left: 216.7107696533203,
                top: 769.8863525390625,
                right: null,
                bottom: null,
                width: 16.059999465942383,
                height: 16.05809211730957,
                child: GeneratedRectangle304Widget(),
              ),
              Positioned(
                left: 170.90960693359375,
                top: 704.378173828125,
                right: null,
                bottom: null,
                width: 107.66221618652344,
                height: 43.06580352783203,
                child: GeneratedGroup166Widget(),
              ),
              Positioned(
                left: 202.24066162109375,
                top: 718.501953125,
                right: null,
                bottom: null,
                width: 50.0,
                height: 25.0,
                child: Generated208337Widget(),
              ),
              Positioned(
                left: 213.74066162109375,
                top: 705.501953125,
                right: null,
                bottom: null,
                width: 27.0,
                height: 19.0,
                child: GeneratedStartWidget(),
              ),
              Positioned(
                left: 176.22662353515625,
                top: 721.42138671875,
                right: null,
                bottom: null,
                width: 97.0281982421875,
                height: 4.010129928588867,
                child: GeneratedGroup165Widget(),
              ),
              Positioned(
                left: 28.53125,
                top: 46.480224609375,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse68Widget28(),
              ),
              Positioned(
                left: 44.0,
                top: 58.980224609375,
                right: null,
                bottom: null,
                width: 8.892169952392578,
                height: 15.0,
                child: GeneratedBackWidget28(),
              ),
              Positioned(
                left: 276.117431640625,
                top: 48.473388671875,
                right: null,
                bottom: null,
                width: 37.0,
                height: 35.0,
                child: GeneratedAAWidget(),
              ),
              Positioned(
                left: 335.30078125,
                top: 51.240478515625,
                right: null,
                bottom: null,
                width: 21.95287322998047,
                height: 15.649643898010254,
                child: GeneratedGroup8Widget1(),
              ),
              Positioned(
                left: 245.0,
                top: 54.473388671875,
                right: null,
                bottom: null,
                width: 15.0,
                height: 18.0,
                child: GeneratedShareWidget3(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 8.554004192352295,
                width: 189.86859130859375,
                height: 6.298901081085205,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: 0.00,
                    z: 0,
                    child: GeneratedRectangle13Widget6()),
              )
            ]),
      ),
    ));
  }
}
