import 'package:flutter/material.dart';
import 'package:flutterapp/test1app/generatedaddcollectionwidget3/generated/GeneratedUnionStrokeWidget13.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/test1app/generatedaddcollectionwidget3/generated/GeneratedUnionWidget378.dart';
import 'package:flutterapp/test1app/generatedaddcollectionwidget3/generated/GeneratedIconWidget301.dart';

/* Component add collection
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAddcollectionWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 17.500001907348633,
      height: 13.999998092651367,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 1.0;
                double scaleX =
                    (constraints.maxWidth * percentWidth) / 17.500001907348633;

                double percentHeight = 1.0;
                double scaleY = (constraints.maxHeight * percentHeight) /
                    13.999998092651367;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: 0,
                      translateY: 0,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedIconWidget301())
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.3530785312022039;
                double scaleX =
                    (constraints.maxWidth * percentWidth) / 6.178874969482422;

                double percentHeight = 0.44134827223481754;
                double scaleY =
                    (constraints.maxHeight * percentHeight) / 6.178874969482422;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.3119000776127322,
                      translateY: constraints.maxHeight * 0.3331473668162982,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedUnionWidget378())
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.3759356770176831;
                double scaleX =
                    (constraints.maxWidth * percentWidth) / 6.5788750648498535;

                double percentHeight = 0.4699197115107552;
                double scaleY = (constraints.maxHeight * percentHeight) /
                    6.5788750648498535;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.3004742976080434,
                      translateY: constraints.maxHeight * 0.31884769968955173,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedUnionStrokeWidget13())
                ]);
              }),
            )
          ]),
    ));
  }
}
