import 'package:flutter/material.dart';
import 'package:flutterapp/test1app/generatedverificationcodewidget/generated/GeneratedVerificationWidget.dart';
import 'package:flutterapp/test1app/generatedverificationcodewidget/generated/GeneratedPleasecheckyourmessageforasixdigitsecuritycodeandenteri.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/test1app/generatedverificationcodewidget/generated/GeneratedGroup365Widget2.dart';
import 'package:flutterapp/test1app/generatedverificationcodewidget/generated/GeneratedButtonWidget9.dart';

/* Frame Verification code
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVerificationcodeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 820.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 94.0,
                top: 124.755615234375,
                right: null,
                bottom: null,
                width: 192.0,
                height: 47.0,
                child: GeneratedVerificationWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.7727913411458334;

                  final double height =
                      constraints.maxHeight * 0.04666506139243521;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.1280234375,
                        y: constraints.maxHeight * 0.2267547607421875,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child:
                              GeneratedPleasecheckyourmessageforasixdigitsecuritycodeandenteri(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 49.0,
                top: 252.09674072265625,
                right: null,
                bottom: null,
                width: 277.0,
                height: 111.786376953125,
                child: GeneratedGroup365Widget2(),
              ),
              Positioned(
                left: 30.0,
                top: 720.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 64.41000366210938,
                child: GeneratedButtonWidget9(),
              )
            ]),
      ),
    ));
  }
}
